## Data pre-procesing

On commence par importer notre data.

In [39]:
train_values <- read.csv("train_values.csv",stringsAsFactors = T)
test_values <- read.csv("test_values.csv",stringsAsFactors = T)
train_labels <- read.csv("train_labels.csv",stringsAsFactors = T)
submission_format <- read.csv("submission_format.csv",stringsAsFactors = T)

On voudrait merge train_values et train_labels par leur colone id_building.

Voir : https://stackoverflow.com/questions/31429736/how-to-join-data-from-2-different-csv-files-in-r

In [4]:
#?merge

In [40]:
data <- merge(train_values,train_labels,by=c('building_id','building_id'),all.x=T)
test <- test_values

On s'assurer que le fusion a bien été éffectuer.

In [34]:
dim(data)
dim(test)

[1] 260601     40

[1] 86868    39

In [7]:
options(repr.matrix.max.cols=50)
data[1:2,]

  building_id geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq
1 4           30             266             1224          1
2 8           17             409            12182          2
  age area_percentage height_percentage land_surface_condition foundation_type
1 25   5              2                 t                      r
2  0  13              7                 t                      r
  roof_type ground_floor_type other_floor_type position plan_configuration
1 n         f                 j                s        d
2 n         f                 q                s        d
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status count_families
1 0                        v                      0
2 0                        v                      1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade
1 0                            0                       2
2 0                            0                       3

On va maintenant suprimer la colone building_id, qui n'apporte pas d'information suplemetaire.

In [41]:
data <- data[,-1]
test <- test[,-1]

On vérifie que l'operation ses bien effectuer.

In [20]:
options(repr.matrix.max.cols=50)
data[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 30             266             1224          1                   25
2 17             409            12182          2                    0
  area_percentage height_percentage land_surface_condition foundation_type
1  5              2                 t                      r
2 13              7                 t                      r
  roof_type ground_floor_type other_floor_type position plan_configuration
1 n         f                 j                s        d
2 n         f                 q                s        d
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status count_families
1 0                        v                      0
2 0                        v                      1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade
1 0                            0                       2
2 0                            0                       3

Vérifion maintenant qu'il n'y a pas de valeur manquante.

Pour ça on puex commencer par regarder le résumer de notre data, pour voir le nombre de valeur NA et si il n'y a pas de caractére vide.

In [24]:
summary(data,maxsum = 11) # maxsum = 11 permet d'afficher jusqu'a 11 valeur pour les facteur

 geo_level_1_id geo_level_2_id   geo_level_3_id  count_floors_pre_eq
 Min.   : 0.0   Min.   :   0.0   Min.   :    0   Min.   :1.00
 1st Qu.: 7.0   1st Qu.: 350.0   1st Qu.: 3073   1st Qu.:2.00
 Median :12.0   Median : 702.0   Median : 6270   Median :2.00
 Mean   :13.9   Mean   : 701.1   Mean   : 6258   Mean   :2.13
 3rd Qu.:21.0   3rd Qu.:1050.0   3rd Qu.: 9412   3rd Qu.:2.00
 Max.   :30.0   Max.   :1427.0   Max.   :12567   Max.   :9.00




      age         area_percentage   height_percentage land_surface_condition
 Min.   :  0.00   Min.   :  1.000   Min.   : 2.000    n: 35528
 1st Qu.: 10.00   1st Qu.:  5.000   1st Qu.: 4.000    o:  8316
 Median : 15.00   Median :  7.000   Median : 5.000    t:216757
 Mean   : 26.54   Mean   :  8.018   Mean   : 5.434
 3rd Qu.: 30.00   3rd Qu.:  9.000   3rd Qu.: 6.000
 Max.   :995.00   Max.   :100.000   Max.   :32.000




 foundation_type roof_type  ground_floor_type other_floor_type position
 h:  1448        n:182842   f:209619          j: 39843         j: 13282
 i: 10579        q: 61576   m:   508          q:165282         o:  2333
 r:219196        x: 16183   v: 24593          s: 12028         s:202090
 u: 14260                   x: 24877          x: 43448         t: 42896
 w: 15118                   z:  1004





 plan_configuration has_superstructure_adobe_mud
 a:   252           Min.   :0.00000
 c:   325           1st Qu.:0.00000
 d:250072           Median :0.00000
 f:    22           Mean   :0.08865
 m:    46           3rd Qu.:0.00000
 n:    38           Max.   :1.00000
 o:   159
 q:  5692
 s:   346
 u:  3649
 has_superstructure_mud_mortar_stone has_superstructure_stone_flag
 Min.   :0.0000                      Min.   :0.00000
 1st Qu.:1.0000                      1st Qu.:0.00000
 Median :1.0000                      Median :0.00000
 Mean   :0.7619                      Mean   :0.03433
 3rd Qu.:1.0000                      3rd Qu.:0.00000
 Max.   :1.0000                      Max.   :1.00000




 has_superstructure_cement_mortar_stone has_superstructure_mud_mortar_brick
 Min.   :0.00000                        Min.   :0.00000
 1st Qu.:0.00000                        1st Qu.:0.00000
 Median :0.00000                        Median :0.00000
 Mean   :0.01823                        Mean   :0.06815
 3rd Qu.:0.00000                        3rd Qu.:0.00000
 Max.   :1.00000                        Max.   :1.00000




 has_superstructure_cement_mortar_brick has_superstructure_timber
 Min.   :0.00000                        Min.   :0.000
 1st Qu.:0.00000                        1st Qu.:0.000
 Median :0.00000                        Median :0.000
 Mean   :0.07527                        Mean   :0.255
 3rd Qu.:0.00000                        3rd Qu.:1.000
 Max.   :1.00000                        Max.   :1.000




 has_superstructure_bamboo has_superstructure_rc_non_engineered
 Min.   :0.00000           Min.   :0.00000
 1st Qu.:0.00000           1st Qu.:0.00000
 Median :0.00000           Median :0.00000
 Mean   :0.08501           Mean   :0.04259
 3rd Qu.:0.00000           3rd Qu.:0.00000
 Max.   :1.00000           Max.   :1.00000




 has_superstructure_rc_engineered has_superstructure_other
 Min.   :0.00000                  Min.   :0.00000
 1st Qu.:0.00000                  1st Qu.:0.00000
 Median :0.00000                  Median :0.00000
 Mean   :0.01586                  Mean   :0.01498
 3rd Qu.:0.00000                  3rd Qu.:0.00000
 Max.   :1.00000                  Max.   :1.00000




 legal_ownership_status count_families   has_secondary_use
 a:  5512               Min.   :0.0000   Min.   :0.0000
 r:  1473               1st Qu.:1.0000   1st Qu.:0.0000
 v:250939               Median :1.0000   Median :0.0000
 w:  2677               Mean   :0.9839   Mean   :0.1119
                        3rd Qu.:1.0000   3rd Qu.:0.0000
                        Max.   :9.0000   Max.   :1.0000




 has_secondary_use_agriculture has_secondary_use_hotel has_secondary_use_rental
 Min.   :0.00000               Min.   :0.00000         Min.   :0.0000
 1st Qu.:0.00000               1st Qu.:0.00000         1st Qu.:0.0000
 Median :0.00000               Median :0.00000         Median :0.0000
 Mean   :0.06438               Mean   :0.03363         Mean   :0.0081
 3rd Qu.:0.00000               3rd Qu.:0.00000         3rd Qu.:0.0000
 Max.   :1.00000               Max.   :1.00000         Max.   :1.0000




 has_secondary_use_institution has_secondary_use_school
 Min.   :0.0000000             Min.   :0.0000000
 1st Qu.:0.0000000             1st Qu.:0.0000000
 Median :0.0000000             Median :0.0000000
 Mean   :0.0009401             Mean   :0.0003607
 3rd Qu.:0.0000000             3rd Qu.:0.0000000
 Max.   :1.0000000             Max.   :1.0000000




 has_secondary_use_industry has_secondary_use_health_post
 Min.   :0.000000           Min.   :0.000000
 1st Qu.:0.000000           1st Qu.:0.000000
 Median :0.000000           Median :0.000000
 Mean   :0.001071           Mean   :0.000188
 3rd Qu.:0.000000           3rd Qu.:0.000000
 Max.   :1.000000           Max.   :1.000000




 has_secondary_use_gov_office has_secondary_use_use_police
 Min.   :0.0000000            Min.   :0.00e+00
 1st Qu.:0.0000000            1st Qu.:0.00e+00
 Median :0.0000000            Median :0.00e+00
 Mean   :0.0001458            Mean   :8.83e-05
 3rd Qu.:0.0000000            3rd Qu.:0.00e+00
 Max.   :1.0000000            Max.   :1.00e+00




 has_secondary_use_other  damage_grade
 Min.   :0.000000        Min.   :1.000
 1st Qu.:0.000000        1st Qu.:2.000
 Median :0.000000        Median :2.000
 Mean   :0.005119        Mean   :2.238
 3rd Qu.:0.000000        3rd Qu.:3.000
 Max.   :1.000000        Max.   :3.000

La variable 'non numérique' prenant le plus de valeur différente est plan_configuration et on vérifier qu'elle prend bien ses 10 valeur attendue. 

Un coup d'oeuil rappide nous dit qu'il n'y a pas de valeur manquante et pas de caractére vide dans les facteur

Petit vérification suplementaire

In [25]:
lapply(data, function(x) sum(is.na(x)))

$geo_level_1_id
[1] 0

$geo_level_2_id
[1] 0

$geo_level_3_id
[1] 0

$count_floors_pre_eq
[1] 0

$age
[1] 0

$area_percentage
[1] 0

$height_percentage
[1] 0

$land_surface_condition
[1] 0

$foundation_type
[1] 0

$roof_type
[1] 0

$ground_floor_type
[1] 0

$other_floor_type
[1] 0

$position
[1] 0

$plan_configuration
[1] 0

$has_superstructure_adobe_mud
[1] 0

$has_superstructure_mud_mortar_stone
[1] 0

$has_superstructure_stone_flag
[1] 0

$has_superstructure_cement_mortar_stone
[1] 0

$has_superstructure_mud_mortar_brick
[1] 0

$has_superstructure_cement_mortar_brick
[1] 0

$has_superstructure_timber
[1] 0

$has_superstructure_bamboo
[1] 0

$has_superstructure_rc_non_engineered
[1] 0

$has_superstructure_rc_engineered
[1] 0

$has_superstructure_other
[1] 0

$legal_ownership_status
[1] 0

$count_families
[1] 0

$has_secondary_use
[1] 0

$has_secondary_use_agriculture
[1] 0

$has_secondary_use_hotel
[1] 0

$has_secondary_use_rental
[1] 0

$has_secondary_use_institution
[1] 0

$has_secondary_use_school
[1] 0

$has_secondary_use_industry
[1] 0

$has_secondary_use_health_post
[1] 0

$has_secondary_use_gov_office
[1] 0

$has_secondary_use_use_police
[1] 0

$has_secondary_use_other
[1] 0

$damage_grade
[1] 0

On traite maintenant les variable categorical

In [26]:
factor_variables <- which(sapply(data[1,],class)=="factor")
factor_variables

land_surface_condition        foundation_type              roof_type
                     8                      9                     10
     ground_floor_type       other_floor_type               position
                    11                     12                     13
    plan_configuration legal_ownership_status
                    14                     26

On va uttiliser caret pour crée des dummies variable mais avant ça on va tranformer la collone damage_grade pour string pour appliquer un problème de multi-classe.

Voir : https://stackoverflow.com/questions/18503177/r-apply-function-on-specific-dataframe-columns

Voir : https://stackoverflow.com/questions/31165015/how-to-convert-integer-to-factor

In [42]:
data[39] <- lapply(data[39], function(x) as.character(x))
data[,39]<-factor(data[,39])

Vérifion qu'on a bien se que l'on voulait

In [43]:
factor_variables <- which(sapply(data[1,],class)=="factor")
factor_variables

land_surface_condition        foundation_type              roof_type
                     8                      9                     10
     ground_floor_type       other_floor_type               position
                    11                     12                     13
    plan_configuration legal_ownership_status           damage_grade
                    14                     26                     39

On peux maintenant uttiliser summary pour compter le nombre de 1,2,3 pour voir si notre data set est unbalance ou non.

In [42]:
summary(data)

 geo_level_1_id geo_level_2_id   geo_level_3_id  count_floors_pre_eq
 Min.   : 0.0   Min.   :   0.0   Min.   :    0   Min.   :1.00
 1st Qu.: 7.0   1st Qu.: 350.0   1st Qu.: 3073   1st Qu.:2.00
 Median :12.0   Median : 702.0   Median : 6270   Median :2.00
 Mean   :13.9   Mean   : 701.1   Mean   : 6258   Mean   :2.13
 3rd Qu.:21.0   3rd Qu.:1050.0   3rd Qu.: 9412   3rd Qu.:2.00
 Max.   :30.0   Max.   :1427.0   Max.   :12567   Max.   :9.00

      age         area_percentage   height_percentage land_surface_condition
 Min.   :  0.00   Min.   :  1.000   Min.   : 2.000    n: 35528
 1st Qu.: 10.00   1st Qu.:  5.000   1st Qu.: 4.000    o:  8316
 Median : 15.00   Median :  7.000   Median : 5.000    t:216757
 Mean   : 26.54   Mean   :  8.018   Mean   : 5.434
 3rd Qu.: 30.00   3rd Qu.:  9.000   3rd Qu.: 6.000
 Max.   :995.00   Max.   :100.000   Max.   :32.000

 foundation_type roof_type  ground_floor_type other_floor_type position
 h:  1448        n:182842   f:209619          j: 39843         j: 13282
 i: 10579        q: 61576   m:   508          q:165282         o:  2333
 r:219196        x: 16183   v: 24593          s: 12028         s:202090
 u: 14260                   x: 24877          x: 43448         t: 42896
 w: 15118                   z:  1004


 plan_configuration has_superstructure_adobe_mud
 d      :250072     Min.   :0.00000
 q      :  5692     1st Qu.:0.00000
 u      :  3649     Median :0.00000
 s      :   346     Mean   :0.08865
 c      :   325     3rd Qu.:0.00000
 a      :   252     Max.   :1.00000
 (Other):   265
 has_superstructure_mud_mortar_stone has_superstructure_stone_flag
 Min.   :0.0000                      Min.   :0.00000
 1st Qu.:1.0000                      1st Qu.:0.00000
 Median :1.0000                      Median :0.00000
 Mean   :0.7619                      Mean   :0.03433
 3rd Qu.:1.0000                      3rd Qu.:0.00000
 Max.   :1.0000                      Max.   :1.00000

 has_superstructure_cement_mortar_stone has_superstructure_mud_mortar_brick
 Min.   :0.00000                        Min.   :0.00000
 1st Qu.:0.00000                        1st Qu.:0.00000
 Median :0.00000                        Median :0.00000
 Mean   :0.01823                        Mean   :0.06815
 3rd Qu.:0.00000                        3rd Qu.:0.00000
 Max.   :1.00000                        Max.   :1.00000

 has_superstructure_cement_mortar_brick has_superstructure_timber
 Min.   :0.00000                        Min.   :0.000
 1st Qu.:0.00000                        1st Qu.:0.000
 Median :0.00000                        Median :0.000
 Mean   :0.07527                        Mean   :0.255
 3rd Qu.:0.00000                        3rd Qu.:1.000
 Max.   :1.00000                        Max.   :1.000

 has_superstructure_bamboo has_superstructure_rc_non_engineered
 Min.   :0.00000           Min.   :0.00000
 1st Qu.:0.00000           1st Qu.:0.00000
 Median :0.00000           Median :0.00000
 Mean   :0.08501           Mean   :0.04259
 3rd Qu.:0.00000           3rd Qu.:0.00000
 Max.   :1.00000           Max.   :1.00000

 has_superstructure_rc_engineered has_superstructure_other
 Min.   :0.00000                  Min.   :0.00000
 1st Qu.:0.00000                  1st Qu.:0.00000
 Median :0.00000                  Median :0.00000
 Mean   :0.01586                  Mean   :0.01498
 3rd Qu.:0.00000                  3rd Qu.:0.00000
 Max.   :1.00000                  Max.   :1.00000

 legal_ownership_status count_families   has_secondary_use
 a:  5512               Min.   :0.0000   Min.   :0.0000
 r:  1473               1st Qu.:1.0000   1st Qu.:0.0000
 v:250939               Median :1.0000   Median :0.0000
 w:  2677               Mean   :0.9839   Mean   :0.1119
                        3rd Qu.:1.0000   3rd Qu.:0.0000
                        Max.   :9.0000   Max.   :1.0000

 has_secondary_use_agriculture has_secondary_use_hotel has_secondary_use_rental
 Min.   :0.00000               Min.   :0.00000         Min.   :0.0000
 1st Qu.:0.00000               1st Qu.:0.00000         1st Qu.:0.0000
 Median :0.00000               Median :0.00000         Median :0.0000
 Mean   :0.06438               Mean   :0.03363         Mean   :0.0081
 3rd Qu.:0.00000               3rd Qu.:0.00000         3rd Qu.:0.0000
 Max.   :1.00000               Max.   :1.00000         Max.   :1.0000

 has_secondary_use_institution has_secondary_use_school
 Min.   :0.0000000             Min.   :0.0000000
 1st Qu.:0.0000000             1st Qu.:0.0000000
 Median :0.0000000             Median :0.0000000
 Mean   :0.0009401             Mean   :0.0003607
 3rd Qu.:0.0000000             3rd Qu.:0.0000000
 Max.   :1.0000000             Max.   :1.0000000

 has_secondary_use_industry has_secondary_use_health_post
 Min.   :0.000000           Min.   :0.000000
 1st Qu.:0.000000           1st Qu.:0.000000
 Median :0.000000           Median :0.000000
 Mean   :0.001071           Mean   :0.000188
 3rd Qu.:0.000000           3rd Qu.:0.000000
 Max.   :1.000000           Max.   :1.000000

 has_secondary_use_gov_office has_secondary_use_use_police
 Min.   :0.0000000            Min.   :0.00e+00
 1st Qu.:0.0000000            1st Qu.:0.00e+00
 Median :0.0000000            Median :0.00e+00
 Mean   :0.0001458            Mean   :8.83e-05
 3rd Qu.:0.0000000            3rd Qu.:0.00e+00
 Max.   :1.0000000            Max.   :1.00e+00

 has_secondary_use_other damage_grade
 Min.   :0.000000        1: 25124
 1st Qu.:0.000000        2:148259
 Median :0.000000        3: 87218
 Mean   :0.005119
 3rd Qu.:0.000000
 Max.   :1.000000

On a bien a faire a un probleme de calssification unbalence se qui étes a prevoir.

On peux maintenant calculer le ratio des damage_grade.

In [5]:
damage_grade_1_ratio <- 25124/260601
damage_grade_2_ratio <- 148259/260601
damage_grade_3_ratio <- 87218/260601

In [55]:
print(damage_grade_1_ratio)
print(damage_grade_2_ratio)
print(damage_grade_3_ratio)

[1] 0.09640792
[1] 0.5689119
[1] 0.3346802

On va maintenant uttiliser caret pour convertir les variable catégarical en bummies variable, il s'agit d'un One-hot encoding.

Voir : https://topepo.github.io/caret/pre-processing.html#dummy

Voir : https://datatricks.co.uk/one-hot-encoding-in-r-three-simple-methods

In [6]:
install.packages("caret")
install.packages("ggplot2")
install.packages("lattice")

Warning message:
“impossible d'accéder à l'index de l'entrepôt https://cran.r-project.org/src/contrib:
  impossible d'ouvrir l'URL 'https://cran.r-project.org/src/contrib/PACKAGES'”
Warning message:
“le package ‘caret’ n'est pas disponible for this version of R

Une version de ce package pour votre version de R est peut-être disponible ailleurs,
Voyez des idées à
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”
Warning message:
“impossible d'accéder à l'index de l'entrepôt https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2:
  impossible d'ouvrir l'URL 'https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES'”
Warning message:
“impossible d'accéder à l'index de l'entrepôt https://cran.r-project.org/src/contrib:
  impossible d'ouvrir l'URL 'https://cran.r-project.org/src/contrib/PACKAGES'”
Warning message:
“le package ‘ggplot2’ n'est pas disponible for this version of R

Une version de ce package pour votre version de R est peut-être disponible ailleurs,
Voyez des idées à
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”
Warning message:
“impossible d'accéder à l'index de l'entrepôt https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2:
  impossible d'ouvrir l'URL 'https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES'”
Warning message:
“impossible d'accéder à l'index de l'entrepôt https://cran.r-project.org/src/contrib:
  impossible d'ouvrir l'URL 'https://cran.r-project.org/src/contrib/PACKAGES'”
Warning message:
“le package ‘lattice’ n'est pas disponible for this version of R

Une version de ce package pour votre version de R est peut-être disponible ailleurs,
Voyez des idées à
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”
Warning message:
“impossible d'accéder à l'index de l'entrepôt https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2:
  impossible d'ouvrir l'URL 'https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES'”

In [7]:
library(ggplot2)
library(lattice)
library(caret)

In [43]:
dummy_data <- dummyVars(" ~ .", data=data)  
data <- data.frame(predict(dummy_data, newdata = data)) 
dummy_test <- dummyVars(" ~ .", data=test) 
test <- data.frame(predict(dummy_test, newdata = test))

Exploront un peux notre nouveau data set

In [44]:
options(repr.matrix.max.cols=100)
data[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 30             266             1224          1                   25
2 17             409            12182          2                    0
  area_percentage height_percentage land_surface_condition.n
1  5              2                 0
2 13              7                 0
  land_surface_condition.o land_surface_condition.t foundation_type.h
1 0                        1                        0
2 0                        1                        0
  foundation_type.i foundation_type.r foundation_type.u foundation_type.w
1 0                 1                 0                 0
2 0                 1                 0                 0
  roof_type.n roof_type.q roof_type.x ground_floor_type.f ground_floor_type.m
1 1           0           0           1                   0
2 1           0           0           1                   0
  ground_floor_type.v ground_floor_type.x ground_floor_type.z
1 0                   0                   0
2 0                   0                   0
  other_floor_type.j other_floor_type.q other_floor_type.s other_floor_type.x
1 1                  0                  0                  0
2 0                  1                  0                  0
  position.j position.o position.s position.t plan_configuration.a
1 0          0          1          0          0
2 0          0          1          0          0
  plan_configuration.c plan_configuration.d plan_configuration.f
1 0                    1                    0
2 0                    1                    0
  plan_configuration.m plan_configuration.n plan_configuration.o
1 0                    0                    0
2 0                    0                    0
  plan_configuration.q plan_configuration.s plan_configuration.u
1 0                    0                    0
2 0                    0                    0
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status.a legal_ownership_status.r
1 0                        0                        0
2 0                        0                        0
  legal_ownership_status.v legal_ownership_status.w count_families
1 1                        0                        0
2 1                        0                        1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade.1
1 0                            0                       0
2 0                            0                       0
  damage_grade.2 damage_grade.3
1 1              0
2 0              1

In [45]:
test[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 17             596            11307          3                   20
2  6             141            11987          2                   25
  area_percentage height_percentage land_surface_condition.n
1  7              6                 0
2 13              5                 0
  land_surface_condition.o land_surface_condition.t foundation_type.h
1 0                        1                        0
2 0                        1                        0
  foundation_type.i foundation_type.r foundation_type.u foundation_type.w
1 0                 1                 0                 0
2 0                 1                 0                 0
  roof_type.n roof_type.q roof_type.x ground_floor_type.f ground_floor_type.m
1 1           0           0           1                   0
2 1           0           0           1                   0
  ground_floor_type.v ground_floor_type.x ground_floor_type.z
1 0                   0                   0
2 0                   0                   0
  other_floor_type.j other_floor_type.q other_floor_type.s other_floor_type.x
1 0                  1                  0                  0
2 0                  1                  0                  0
  position.j position.o position.s position.t plan_configuration.a
1 0          0          1          0          0
2 0          0          1          0          0
  plan_configuration.c plan_configuration.d plan_configuration.f
1 0                    1                    0
2 0                    1                    0
  plan_configuration.m plan_configuration.n plan_configuration.o
1 0                    0                    0
2 0                    0                    0
  plan_configuration.q plan_configuration.s plan_configuration.u
1 0                    0                    0
2 0                    0                    0
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status.a legal_ownership_status.r
1 0                        0                        0
2 0                        0                        0
  legal_ownership_status.v legal_ownership_status.w count_families
1 1                        0                        1
2 1                        0                        1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 1                 1                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other
1 0                            0
2 0                            0

In [10]:
dim(data)

[1] 260601     71

In [162]:
summary(data)

 geo_level_1_id geo_level_2_id   geo_level_3_id  count_floors_pre_eq
 Min.   : 0.0   Min.   :   0.0   Min.   :    0   Min.   :1.00
 1st Qu.: 7.0   1st Qu.: 350.0   1st Qu.: 3073   1st Qu.:2.00
 Median :12.0   Median : 702.0   Median : 6270   Median :2.00
 Mean   :13.9   Mean   : 701.1   Mean   : 6258   Mean   :2.13
 3rd Qu.:21.0   3rd Qu.:1050.0   3rd Qu.: 9412   3rd Qu.:2.00
 Max.   :30.0   Max.   :1427.0   Max.   :12567   Max.   :9.00
      age         area_percentage   height_percentage land_surface_condition.n
 Min.   :  0.00   Min.   :  1.000   Min.   : 2.000    Min.   :0.0000
 1st Qu.: 10.00   1st Qu.:  5.000   1st Qu.: 4.000    1st Qu.:0.0000
 Median : 15.00   Median :  7.000   Median : 5.000    Median :0.0000
 Mean   : 26.54   Mean   :  8.018   Mean   : 5.434    Mean   :0.1363
 3rd Qu.: 30.00   3rd Qu.:  9.000   3rd Qu.: 6.000    3rd Qu.:0.0000
 Max.   :995.00   Max.   :100.000   Max.   :32.000    Max.   :1.0000
 land_surface_condition.o land_surface_condition.t foundation_type.h
 Min.   :0.00000          Min.   :0.0000           Min.   :0.000000
 1st Qu.:0.00000          1st Qu.:1.0000           1st Qu.:0.000000
 Median :0.00000          Median :1.0000           Median :0.000000
 Mean   :0.03191          Mean   :0.8318           Mean   :0.005556
 3rd Qu.:0.00000          3rd Qu.:1.0000           3rd Qu.:0.000000
 Max.   :1.00000          Max.   :1.0000           Max.   :1.000000
 foundation_type.i foundation_type.r foundation_type.u foundation_type.w
 Min.   :0.00000   Min.   :0.0000    Min.   :0.00000   Min.   :0.00000
 1st Qu.:0.00000   1st Qu.:1.0000    1st Qu.:0.00000   1st Qu.:0.00000
 Median :0.00000   Median :1.0000    Median :0.00000   Median :0.00000
 Mean   :0.04059   Mean   :0.8411    Mean   :0.05472   Mean   :0.05801
 3rd Qu.:0.00000   3rd Qu.:1.0000    3rd Qu.:0.00000   3rd Qu.:0.00000
 Max.   :1.00000   Max.   :1.0000    Max.   :1.00000   Max.   :1.00000
  roof_type.n      roof_type.q      roof_type.x     ground_floor_type.f
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:1.0000
 Median :1.0000   Median :0.0000   Median :0.0000   Median :1.0000
 Mean   :0.7016   Mean   :0.2363   Mean   :0.0621   Mean   :0.8044
 3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:1.0000
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000
 ground_floor_type.m ground_floor_type.v ground_floor_type.x
 Min.   :0.000000    Min.   :0.00000     Min.   :0.00000
 1st Qu.:0.000000    1st Qu.:0.00000     1st Qu.:0.00000
 Median :0.000000    Median :0.00000     Median :0.00000
 Mean   :0.001949    Mean   :0.09437     Mean   :0.09546
 3rd Qu.:0.000000    3rd Qu.:0.00000     3rd Qu.:0.00000
 Max.   :1.000000    Max.   :1.00000     Max.   :1.00000
 ground_floor_type.z other_floor_type.j other_floor_type.q other_floor_type.s
 Min.   :0.000000    Min.   :0.0000     Min.   :0.0000     Min.   :0.00000
 1st Qu.:0.000000    1st Qu.:0.0000     1st Qu.:0.0000     1st Qu.:0.00000
 Median :0.000000    Median :0.0000     Median :1.0000     Median :0.00000
 Mean   :0.003853    Mean   :0.1529     Mean   :0.6342     Mean   :0.04615
 3rd Qu.:0.000000    3rd Qu.:0.0000     3rd Qu.:1.0000     3rd Qu.:0.00000
 Max.   :1.000000    Max.   :1.0000     Max.   :1.0000     Max.   :1.00000
 other_floor_type.x   position.j        position.o         position.s
 Min.   :0.0000     Min.   :0.00000   Min.   :0.000000   Min.   :0.0000
 1st Qu.:0.0000     1st Qu.:0.00000   1st Qu.:0.000000   1st Qu.:1.0000
 Median :0.0000     Median :0.00000   Median :0.000000   Median :1.0000
 Mean   :0.1667     Mean   :0.05097   Mean   :0.008952   Mean   :0.7755
 3rd Qu.:0.0000     3rd Qu.:0.00000   3rd Qu.:0.000000   3rd Qu.:1.0000
 Max.   :1.0000     Max.   :1.00000   Max.   :1.000000   Max.   :1.0000
   position.t     plan_configuration.a plan_configuration.c
 Min.   :0.0000   Min.   :0.000000     Min.   :0.000000
 1st Qu.:0.0000   1st Qu.:0.000000     1st Qu.:0.000000
 Median :0.0000   Median :0.000000     Median :0.000000
 Mean   :0.1646   Mean   :0.000967     Mean   :0.001247
 3rd Qu.:0.0000   3rd Qu.:0.000000     3rd Qu.:0.000000
 Max.   :1.0000   Max.   :1.000000     Max.   :1.000000
 plan_configuration.d plan_configuration.f plan_configuration.m
 Min.   :0.0000       Min.   :0.00e+00     Min.   :0.0000000
 1st Qu.:1.0000       1st Qu.:0.00e+00     1st Qu.:0.0000000
 Median :1.0000       Median :0.00e+00     Median :0.0000000
 Mean   :0.9596       Mean   :8.44e-05     Mean   :0.0001765
 3rd Qu.:1.0000       3rd Qu.:0.00e+00     3rd Qu.:0.0000000
 Max.   :1.0000       Max.   :1.00e+00     Max.   :1.0000000
 plan_configuration.n plan_configuration.o plan_configuration.q
 Min.   :0.0000000    Min.   :0.0000000    Min.   :0.00000
 1st Qu.:0.0000000    1st Qu.:0.0000000    1st Qu.:0.00000
 Median :0.0000000    Median :0.0000000    Median :0.00000
 Mean   :0.0001458    Mean   :0.0006101    Mean   :0.02184
 3rd Qu.:0.0000000    3rd Qu.:0.0000000    3rd Qu.:0.00000
 Max.   :1.0000000    Max.   :1.0000000    Max.   :1.00000
 plan_configuration.s plan_configuration.u has_superstructure_adobe_mud
 Min.   :0.000000     Min.   :0.000        Min.   :0.00000
 1st Qu.:0.000000     1st Qu.:0.000        1st Qu.:0.00000
 Median :0.000000     Median :0.000        Median :0.00000
 Mean   :0.001328     Mean   :0.014        Mean   :0.08865
 3rd Qu.:0.000000     3rd Qu.:0.000        3rd Qu.:0.00000
 Max.   :1.000000     Max.   :1.000        Max.   :1.00000
 has_superstructure_mud_mortar_stone has_superstructure_stone_flag
 Min.   :0.0000                      Min.   :0.00000
 1st Qu.:1.0000                      1st Qu.:0.00000
 Median :1.0000                      Median :0.00000
 Mean   :0.7619                      Mean   :0.03433
 3rd Qu.:1.0000                      3rd Qu.:0.00000
 Max.   :1.0000                      Max.   :1.00000
 has_superstructure_cement_mortar_stone has_superstructure_mud_mortar_brick
 Min.   :0.00000                        Min.   :0.00000
 1st Qu.:0.00000                        1st Qu.:0.00000
 Median :0.00000                        Median :0.00000
 Mean   :0.01823                        Mean   :0.06815
 3rd Qu.:0.00000                        3rd Qu.:0.00000
 Max.   :1.00000                        Max.   :1.00000
 has_superstructure_cement_mortar_brick has_superstructure_timber
 Min.   :0.00000                        Min.   :0.000
 1st Qu.:0.00000                        1st Qu.:0.000
 Median :0.00000                        Median :0.000
 Mean   :0.07527                        Mean   :0.255
 3rd Qu.:0.00000                        3rd Qu.:1.000
 Max.   :1.00000                        Max.   :1.000
 has_superstructure_bamboo has_superstructure_rc_non_engineered
 Min.   :0.00000           Min.   :0.00000
 1st Qu.:0.00000           1st Qu.:0.00000
 Median :0.00000           Median :0.00000
 Mean   :0.08501           Mean   :0.04259
 3rd Qu.:0.00000           3rd Qu.:0.00000
 Max.   :1.00000           Max.   :1.00000
 has_superstructure_rc_engineered has_superstructure_other
 Min.   :0.00000                  Min.   :0.00000
 1st Qu.:0.00000                  1st Qu.:0.00000
 Median :0.00000                  Median :0.00000
 Mean   :0.01586                  Mean   :0.01498
 3rd Qu.:0.00000                  3rd Qu.:0.00000
 Max.   :1.00000                  Max.   :1.00000
 legal_ownership_status.a legal_ownership_status.r legal_ownership_status.v
 Min.   :0.00000          Min.   :0.000000         Min.   :0.0000
 1st Qu.:0.00000          1st Qu.:0.000000         1st Qu.:1.0000
 Median :0.00000          Median :0.000000         Median :1.0000
 Mean   :0.02115          Mean   :0.005652         Mean   :0.9629
 3rd Qu.:0.00000          3rd Qu.:0.000000         3rd Qu.:1.0000
 Max.   :1.00000          Max.   :1.000000         Max.   :1.0000
 legal_ownership_status.w count_families   has_secondary_use
 Min.   :0.00000          Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.00000          1st Qu.:1.0000   1st Qu.:0.0000
 Median :0.00000          Median :1.0000   Median :0.0000
 Mean   :0.01027          Mean   :0.9839   Mean   :0.1119
 3rd Qu.:0.00000          3rd Qu.:1.0000   3rd Qu.:0.0000
 Max.   :1.00000          Max.   :9.0000   Max.   :1.0000
 has_secondary_use_agriculture has_secondary_use_hotel has_secondary_use_rental
 Min.   :0.00000               Min.   :0.00000         Min.   :0.0000
 1st Qu.:0.00000               1st Qu.:0.00000         1st Qu.:0.0000
 Median :0.00000               Median :0.00000         Median :0.0000
 Mean   :0.06438               Mean   :0.03363         Mean   :0.0081
 3rd Qu.:0.00000               3rd Qu.:0.00000         3rd Qu.:0.0000
 Max.   :1.00000               Max.   :1.00000         Max.   :1.0000
 has_secondary_use_institution has_secondary_use_school
 Min.   :0.0000000             Min.   :0.0000000
 1st Qu.:0.0000000             1st Qu.:0.0000000
 Median :0.0000000             Median :0.0000000
 Mean   :0.0009401             Mean   :0.0003607
 3rd Qu.:0.0000000             3rd Qu.:0.0000000
 Max.   :1.0000000             Max.   :1.0000000
 has_secondary_use_industry has_secondary_use_health_post
 Min.   :0.000000           Min.   :0.000000
 1st Qu.:0.000000           1st Qu.:0.000000
 Median :0.000000           Median :0.000000
 Mean   :0.001071           Mean   :0.000188
 3rd Qu.:0.000000           3rd Qu.:0.000000
 Max.   :1.000000           Max.   :1.000000
 has_secondary_use_gov_office has_secondary_use_use_police
 Min.   :0.0000000            Min.   :0.00e+00
 1st Qu.:0.0000000            1st Qu.:0.00e+00
 Median :0.0000000            Median :0.00e+00
 Mean   :0.0001458            Mean   :8.83e-05
 3rd Qu.:0.0000000            3rd Qu.:0.00e+00
 Max.   :1.0000000            Max.   :1.00e+00
 has_secondary_use_other damage_grade.1    damage_grade.2   damage_grade.3
 Min.   :0.000000        Min.   :0.00000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.000000        1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.000000        Median :0.00000   Median :1.0000   Median :0.0000
 Mean   :0.005119        Mean   :0.09641   Mean   :0.5689   Mean   :0.3347
 3rd Qu.:0.000000        3rd Qu.:0.00000   3rd Qu.:1.0000   3rd Qu.:1.0000
 Max.   :1.000000        Max.   :1.00000   Max.   :1.0000   Max.   :1.0000

## Test submision file

On va générer un fichier pour le soumetre sur DrivenData en générant aléatoirement les damage_drade selon le ration precedament obtenue.

In [63]:
damage_grade_1_ratio + damage_grade_2_ratio + damage_grade_3_ratio

[1] 1

In [107]:
dim(submission_format)

[1] 86868     2

In [125]:
#submission_format[2] <- sample(1:3, size = 86868, replace = TRUE, prob = c(damage_grade_1_ratio,damage_grade_2_ratio,damage_grade_3_ratio))

In [126]:
#write.csv(submission_format, file = "submission_format_random_3.csv", row.names = FALSE)

## Feature selection

### Zero- and Near Zero-Variance Predictors

Voir : https://topepo.github.io/caret/pre-processing.html#zero--and-near-zero-variance-predictors

Peux etres un problème pour le model linéaire apparament mais pas pour decison tree

In [46]:
nzv <- nearZeroVar(data, saveMetrics= TRUE)
nzv[nzv$nzv,][1:36,]

                                       freqRatio   percentUnique zeroVar nzv
land_surface_condition.o                  30.33730 0.0007674568  FALSE   TRUE
foundation_type.h                        178.97307 0.0007674568  FALSE   TRUE
foundation_type.i                         23.63380 0.0007674568  FALSE   TRUE
ground_floor_type.m                      511.99409 0.0007674568  FALSE   TRUE
ground_floor_type.z                      258.56275 0.0007674568  FALSE   TRUE
other_floor_type.s                        20.66620 0.0007674568  FALSE   TRUE
position.o                               110.70210 0.0007674568  FALSE   TRUE
plan_configuration.a                    1033.13095 0.0007674568  FALSE   TRUE
plan_configuration.c                     800.84923 0.0007674568  FALSE   TRUE
plan_configuration.d                      23.75078 0.0007674568  FALSE   TRUE
plan_configuration.f                   11844.50000 0.0007674568  FALSE   TRUE
plan_configuration.m                    5664.23913 0.0007674568  FALSE   TRUE
plan_configuration.n                    6856.92105 0.0007674568  FALSE   TRUE
plan_configuration.o                    1638.00000 0.0007674568  FALSE   TRUE
plan_configuration.q                      44.78373 0.0007674568  FALSE   TRUE
plan_configuration.s                     752.18208 0.0007674568  FALSE   TRUE
plan_configuration.u                      70.41710 0.0007674568  FALSE   TRUE
has_superstructure_stone_flag             28.12719 0.0007674568  FALSE   TRUE
has_superstructure_cement_mortar_stone    53.84028 0.0007674568  FALSE   TRUE
has_superstructure_rc_non_engineered      22.47968 0.0007674568  FALSE   TRUE
has_superstructure_rc_engineered          62.05371 0.0007674568  FALSE   TRUE
has_superstructure_other                  65.73521 0.0007674568  FALSE   TRUE
legal_ownership_status.a                  46.27885 0.0007674568  FALSE   TRUE
legal_ownership_status.r                 175.91853 0.0007674568  FALSE   TRUE
legal_ownership_status.v                  25.97174 0.0007674568  FALSE   TRUE
legal_ownership_status.w                  96.34815 0.0007674568  FALSE   TRUE
has_secondary_use_hotel                   28.73879 0.0007674568  FALSE   TRUE
has_secondary_use_rental                 122.44908 0.0007674568  FALSE   TRUE
has_secondary_use_institution           1062.67755 0.0007674568  FALSE   TRUE
has_secondary_use_school                2771.35106 0.0007674568  FALSE   TRUE
has_secondary_use_industry               933.05376 0.0007674568  FALSE   TRUE
has_secondary_use_health_post           5317.38776 0.0007674568  FALSE   TRUE
has_secondary_use_gov_office            6856.92105 0.0007674568  FALSE   TRUE
has_secondary_use_use_police           11329.47826 0.0007674568  FALSE   TRUE
has_secondary_use_other                  194.35307 0.0007674568  FALSE   TRUE
NA                                              NA           NA     NA     NA

In [14]:
dim(data)

[1] 260601     71

In [232]:
nzv <- nearZeroVar(data)
filteredDescr <- data[, -nzv]
test <- test[,-nzv]
dim(filteredDescr)
dim(test)

[1] 260601     36

[1] 86868    24

In [231]:
filteredDescr[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 30             266             1224          1                   25
2 17             409            12182          2                    0
  area_percentage height_percentage land_surface_condition.n
1  5              2                 0
2 13              7                 0
  land_surface_condition.t foundation_type.r foundation_type.u
1 1                        1                 0
2 1                        1                 0
  foundation_type.w roof_type.n roof_type.q roof_type.x ground_floor_type.f
1 0                 1           0           0           1
2 0                 1           0           0           1
  ground_floor_type.v ground_floor_type.x other_floor_type.j other_floor_type.q
1 0                   0                   1                  0
2 0                   0                   0                  1
  other_floor_type.x position.j position.s position.t
1 0                  0          1          0
2 0                  0          1          0
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo count_families
1 0                         0                         0
2 0                         0                         1
  has_secondary_use has_secondary_use_agriculture damage_grade.1 damage_grade.2
1 0                 0                             0              1
2 0                 0                             0              0
  damage_grade.3
1 0
2 1

### Identifying Correlated Predictors

On elever les variable fortement corréler. 

Mais je pense pas qu'ici sa sera uttile.

In [141]:
descrCor <-  cor(filteredDescr)
highCorr <- sum(abs(descrCor[upper.tri(descrCor)]) > .999)

In [143]:
highCorr

[1] 0

In [166]:
descrCor <- cor(filteredDescr)
summary(descrCor[upper.tri(descrCor)])

     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-0.883396 -0.047275 -0.004061 -0.011432  0.039344  0.772734

In [167]:
highlyCorDescr <- findCorrelation(descrCor, cutoff = .75)
filteredDescr <- filteredDescr[,-highlyCorDescr]
descrCor2 <- cor(filteredDescr)
summary(descrCor2[upper.tri(descrCor2)])

     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-0.658725 -0.043182 -0.003916 -0.006108  0.037400  0.739059

### Linear Dependencies

In [87]:
findLinearCombos(data)

$linearCombos
$linearCombos[[1]]
[1] 15  8  9 10 11 12 13 14

$linearCombos[[2]]
[1] 18  8  9 10 16 17

$linearCombos[[3]]
[1] 23  8  9 10 19 20 21 22

$linearCombos[[4]]
[1] 27  8  9 10 24 25 26

$linearCombos[[5]]
[1] 31  8  9 10 28 29 30

$linearCombos[[6]]
 [1] 41  8  9 10 32 33 34 35 36 37 38 39 40

$linearCombos[[7]]
[1] 56  8  9 10 53 54 55

$linearCombos[[8]]
[1] 71  8  9 10 69 70


$remove
[1] 15 18 23 27 31 41 56 71

In [90]:
colnames(filteredDescr)

 [1] "geo_level_1_id"
 [2] "geo_level_2_id"
 [3] "geo_level_3_id"
 [4] "count_floors_pre_eq"
 [5] "age"
 [6] "area_percentage"
 [7] "height_percentage"
 [8] "land_surface_condition.n"
 [9] "land_surface_condition.t"
[10] "foundation_type.r"
[11] "foundation_type.u"
[12] "foundation_type.w"
[13] "roof_type.n"
[14] "roof_type.q"
[15] "roof_type.x"
[16] "ground_floor_type.f"
[17] "ground_floor_type.v"
[18] "ground_floor_type.x"
[19] "other_floor_type.j"
[20] "other_floor_type.q"
[21] "other_floor_type.x"
[22] "position.j"
[23] "position.s"
[24] "position.t"
[25] "has_superstructure_adobe_mud"
[26] "has_superstructure_mud_mortar_stone"
[27] "has_superstructure_mud_mortar_brick"
[28] "has_superstructure_cement_mortar_brick"
[29] "has_superstructure_timber"
[30] "has_superstructure_bamboo"
[31] "count_families"
[32] "has_secondary_use"
[33] "has_secondary_use_agriculture"
[34] "damage_grade.1"
[35] "damage_grade.2"
[36] "damage_grade.3"

In [91]:
dim(filteredDescr)

[1] 260601     36

In [88]:
findLinearCombos(filteredDescr)

$linearCombos
$linearCombos[[1]]
[1] 36 13 14 15 34 35


$remove
[1] 36

In [95]:
colnames(X)[c(16,1,14,15)]

[1] "roof_type.x" ""            "roof_type.n" "roof_type.q"

In [89]:
findLinearCombos(X)

$linearCombos
$linearCombos[[1]]
[1] 16  1 14 15


$remove
[1] 16

In [83]:
dim(X)

[1] 260601     34

In [97]:
info <- findLinearCombos(X)

# Faire des teste sur un sous-ensemble du data set pour diminuer le temps de compilation

In [16]:
set.seed(2)
newdata <- filteredDescr[sample(nrow(data),10000),]

In [17]:
dim(newdata)

[1] 10000    36

In [18]:
options(repr.plot.width=20, repr.plot.height=10)
set.seed(3)

X<-newdata[,setdiff(colnames(newdata),"damage_grade.1")]
Y<-newdata[,"damage_grade.1"]

N<-nrow(X)    #Number of examples
n<-ncol(X)    #Number of input variables

Correlation with the output

In [19]:
# drop = F is used to preserve the structure of the data as data.frame (see https://www.r-bloggers.com/2018/02/r-tip-use-drop-false-with-data-frames/)
CV_folds <- 10

size_CV <-floor(N/CV_folds)

CV_err<-matrix(0,nrow=n,ncol=CV_folds)

for (i in 1:CV_folds) {
    
    idx_ts<-(((i-1)*size_CV+1):(i*size_CV))  ### idx_ts represents the indices of the test set the i-th fold
    X_ts<-X[idx_ts,]  
    Y_ts<-Y[idx_ts]  
     
    idx_tr<-setdiff(1:N,idx_ts) ### idx_tr represents  indices of the training sefor the i-th fold
    X_tr<-X[idx_tr,]
    Y_tr<-Y[idx_tr]                          
    
    # Compute correlation across all the input variables and the target variable
    correlation_vector <-abs(cor(X_tr,Y_tr))
    # Rank variables according to correlation with the output
    correlation_ranking_idx <-sort(correlation_vector,dec=T,index.return=T)$ix

}  

correlation_ranking_idx
colnames(X)[correlation_ranking_idx]

 [1] 34 10 17 15 26 16 28 35 20 19 12 11  1  6  4 13 25 14 27 32  5  2 33 31 21
[26]  8  7  9 30 29 22  3 24 23 18

 [1] "damage_grade.2"
 [2] "foundation_type.r"
 [3] "ground_floor_type.v"
 [4] "roof_type.x"
 [5] "has_superstructure_mud_mortar_stone"
 [6] "ground_floor_type.f"
 [7] "has_superstructure_cement_mortar_brick"
 [8] "damage_grade.3"
 [9] "other_floor_type.q"
[10] "other_floor_type.j"
[11] "foundation_type.w"
[12] "foundation_type.u"
[13] "geo_level_1_id"
[14] "area_percentage"
[15] "count_floors_pre_eq"
[16] "roof_type.n"
[17] "has_superstructure_adobe_mud"
[18] "roof_type.q"
[19] "has_superstructure_mud_mortar_brick"
[20] "has_secondary_use"
[21] "age"
[22] "geo_level_2_id"
[23] "has_secondary_use_agriculture"
[24] "count_families"
[25] "other_floor_type.x"
[26] "land_surface_condition.n"
[27] "height_percentage"
[28] "land_surface_condition.t"
[29] "has_superstructure_bamboo"
[30] "has_superstructure_timber"
[31] "position.j"
[32] "geo_level_3_id"
[33] "position.t"
[34] "position.s"
[35] "ground_floor_type.x"

mRMR

In [20]:
# drop = F is used to preserve the structure of the data as data.frame (see https://www.r-bloggers.com/2018/02/r-tip-use-drop-false-with-data-frames/)

CV_folds <- 10

size_CV <-floor(N/CV_folds)

CV_err<-matrix(0,nrow=n,ncol=CV_folds)

for (i in 1:CV_folds) {
    
    idx_ts<-(((i-1)*size_CV+1):(i*size_CV))  ### idx_ts represents the indices of the test set the i-th fold
    X_ts<-X[idx_ts,]  
    Y_ts<-Y[idx_ts]  
     
    idx_tr<-setdiff(1:N,idx_ts) ### idx_tr represents  indices of the training sefor the i-th fold
    X_tr<-X[idx_tr,]
    Y_tr<-Y[idx_tr]                          
    
    # Computing the correlation between input variables and output variable on the training set
    correlation<-abs(cor(X_tr,Y_tr))
    
    # Initialization : No variables are selected and all the variables are candidates
    selected<-c()
    candidates<-1:n
    
    #mRMR ranks the variables by taking account not only the correlation with the output, but also by avoiding redudant variables
    for (j in 1:n) {
        redundancy_score<-numeric(length(candidates))
        
        if (length(selected)>0) {
            # Compute the correlation between the selected variables and the candidates on the training set
            cor_selected_candidates<-cor(X_tr[,selected,drop=F],X_tr[,candidates,drop=F])
            # Compute the mean correlation for each candidate variable, across the selected variables
            redundancy_score<-apply(cor_selected_candidates,2,mean)
        }
        
        # mRMR: minimum Redundancy Maximum Relevancy
        mRMR_score<-correlation[candidates]-redundancy_score
        
        # Select the candidate variable that maximises the mRMR score
        selected_current<-candidates[which.max(mRMR_score)]
        selected<-c(selected,selected_current)
        
        # Remove the selected variables from the candidates
        candidates<-setdiff(candidates,selected_current)
    }
    
    ranking <- selected

}  

selected
colnames(X)[selected]

 [1] 34 35 17 10 12 15 26 16 28 20 19 11  4  1 13 14  6 25 21  2 32 27  8  9  5
[26] 18 31 30 23 24 22 33  3 29  7

 [1] "damage_grade.2"
 [2] "damage_grade.3"
 [3] "ground_floor_type.v"
 [4] "foundation_type.r"
 [5] "foundation_type.w"
 [6] "roof_type.x"
 [7] "has_superstructure_mud_mortar_stone"
 [8] "ground_floor_type.f"
 [9] "has_superstructure_cement_mortar_brick"
[10] "other_floor_type.q"
[11] "other_floor_type.j"
[12] "foundation_type.u"
[13] "count_floors_pre_eq"
[14] "geo_level_1_id"
[15] "roof_type.n"
[16] "roof_type.q"
[17] "area_percentage"
[18] "has_superstructure_adobe_mud"
[19] "other_floor_type.x"
[20] "geo_level_2_id"
[21] "has_secondary_use"
[22] "has_superstructure_mud_mortar_brick"
[23] "land_surface_condition.n"
[24] "land_surface_condition.t"
[25] "age"
[26] "ground_floor_type.x"
[27] "count_families"
[28] "has_superstructure_bamboo"
[29] "position.s"
[30] "position.t"
[31] "position.j"
[32] "has_secondary_use_agriculture"
[33] "geo_level_3_id"
[34] "has_superstructure_timber"
[35] "height_percentage"

### Linear Regression of an Indicator Matrix

Voir : chapitre 4.2 The elements of statistical learning

In [13]:
dim(filteredDescr)

[1] 260601     36

In [136]:
X <- filteredDescr[,setdiff(colnames(filteredDescr),c("damage_grade.1","damage_grade.2","damage_grade.3"))]
Y <- filteredDescr[,c("damage_grade.1","damage_grade.2","damage_grade.3")]

In [137]:
X <- as.matrix(X)
Y <- as.matrix(Y)

In [140]:
highCorr <- sum(abs(X[upper.tri(X)]) > .999)
highCorr

[1] 168

In [ ]:
highlyCorDescr <- findCorrelation(descrCor, cutoff = .75)

In [138]:
cor(X)

                                       geo_level_1_id geo_level_2_id
geo_level_1_id                          1.000000000   -0.0614048534
geo_level_2_id                         -0.061404853    1.0000000000
geo_level_3_id                          0.002718445    0.0009210931
count_floors_pre_eq                    -0.089363579    0.0477296944
age                                    -0.003907635    0.0125938406
area_percentage                         0.071158150   -0.0494432851
height_percentage                      -0.063474054    0.0355163893
land_surface_condition.n               -0.028659774    0.0335240812
land_surface_condition.t                0.030337373   -0.0331909305
foundation_type.r                      -0.188060656    0.0979804383
foundation_type.u                       0.077188739   -0.0625135975
foundation_type.w                       0.212048338   -0.0428306290
roof_type.n                            -0.027454027    0.0828019233
roof_type.q                             0.002146344   -0.0510354855
roof_type.x                             0.048272296   -0.0671518525
ground_floor_type.f                    -0.075405167    0.0993266489
ground_floor_type.v                     0.110562502   -0.0782788854
ground_floor_type.x                    -0.009462225   -0.0554279422
other_floor_type.j                      0.112915473   -0.0408807025
other_floor_type.q                     -0.130032989    0.0708999095
other_floor_type.x                      0.047570212   -0.0236763998
position.j                             -0.004850808   -0.0065801841
position.s                              0.024287002   -0.0054186604
position.t                             -0.023790506    0.0089714301
has_superstructure_adobe_mud           -0.018245465    0.0158328554
has_superstructure_mud_mortar_stone    -0.152037764    0.0764913251
has_superstructure_mud_mortar_brick    -0.028853680    0.0142456373
has_superstructure_cement_mortar_brick  0.134121409   -0.0798752255
has_superstructure_timber               0.144985347   -0.0239268842
has_superstructure_bamboo               0.074168845   -0.0325884947
count_families                          0.035108327   -0.0124390487
has_secondary_use                      -0.010427924   -0.0015187196
has_secondary_use_agriculture          -0.019785829    0.0175222260
                                       geo_level_3_id count_floors_pre_eq
geo_level_1_id                          0.0027184451  -0.089363579
geo_level_2_id                          0.0009210931   0.047729694
geo_level_3_id                          1.0000000000  -0.021646316
count_floors_pre_eq                    -0.0216463160   1.000000000
age                                    -0.0063845871   0.086668031
area_percentage                        -0.0056426426   0.101071177
height_percentage                      -0.0245067672   0.772734385
land_surface_condition.n                0.0120125446  -0.038525062
land_surface_condition.t               -0.0180251737   0.046218344
foundation_type.r                       0.0014559316   0.131691925
foundation_type.u                      -0.0070691581  -0.095874163
foundation_type.w                       0.0106205250  -0.133956351
roof_type.n                             0.0020520653  -0.099278162
roof_type.q                             0.0061039918   0.085248635
roof_type.x                            -0.0146348083   0.038167098
ground_floor_type.f                     0.0089158477   0.057356319
ground_floor_type.v                    -0.0043249249  -0.070247038
ground_floor_type.x                    -0.0068700918   0.001164259
other_floor_type.j                      0.0091603699  -0.658161110
other_floor_type.q                      0.0007060090   0.353822847
other_floor_type.x                     -0.0028117893   0.081221899
position.j                             -0.0157317772   0.246396152
position.s                              0.0173439398  -0.229465245
position.t                             -0.0051989509   0.056249239
has_superstructure_adobe_mud           -0.0157321636   0.174851702
has_superstructure_mud_mortar_stone     0.0262943509  -0.027115976
has_superstructure_mud_mortar_brick    -0.0232784539   0.257278702
has_superstructure_cement_mortar_brick -0.0051157067  -0.085820914
has_superstructure_timber              -0.0039160333  -0.056637092
has_superstructure_bamboo               0.0061433015  -0.070487236
count_families                         -0.0024786104   0.086585990
has_secondary_use                       0.0073754394   0.052125461
has_secondary_use_agriculture           0.0159948483  -0.005293656
                                       age          area_percentage
geo_level_1_id                         -0.003907635  0.071158150
geo_level_2_id                          0.012593841 -0.049443285
geo_level_3_id                         -0.006384587 -0.005642643
count_floors_pre_eq                     0.086668031  0.101071177
age                                     1.000000000 -0.004322511
area_percentage                        -0.004322511  1.000000000
height_percentage                       0.061073549  0.196645285
land_surface_condition.n               -0.012086677 -0.028422431
land_surface_condition.t                0.018434008  0.025817226
foundation_type.r                       0.072639710 -0.198505861
foundation_type.u                      -0.020130954  0.126860116
foundation_type.w                      -0.051183992 -0.064849187
roof_type.n                             0.022504167 -0.148760169
roof_type.q                            -0.001465003 -0.043029800
roof_type.x                            -0.040087118  0.357776863
ground_floor_type.f                     0.043667780 -0.258259122
ground_floor_type.v                    -0.052341946  0.328150406
ground_floor_type.x                    -0.006342776  0.020847497
other_floor_type.j                     -0.051633633 -0.037512106
other_floor_type.q                      0.054615080 -0.129556728
other_floor_type.x                     -0.003244466  0.024702248
position.j                              0.056347761  0.070491599
position.s                             -0.049696235 -0.047299540
position.t                              0.004849855  0.013991511
has_superstructure_adobe_mud            0.068032466  0.026286747
has_superstructure_mud_mortar_stone     0.001321263 -0.225540553
has_superstructure_mud_mortar_brick     0.079525443  0.053361532
has_superstructure_cement_mortar_brick -0.036991916  0.210800360
has_superstructure_timber               0.005855425 -0.053965116
has_superstructure_bamboo              -0.008374469 -0.031641234
count_families                          0.005309281  0.088630187
has_secondary_use                      -0.008787676  0.122400610
has_secondary_use_agriculture          -0.002194027 -0.016477524
                                       height_percentage
geo_level_1_id                         -0.063474054
geo_level_2_id                          0.035516389
geo_level_3_id                         -0.024506767
count_floors_pre_eq                     0.772734385
age                                     0.061073549
area_percentage                         0.196645285
height_percentage                       1.000000000
land_surface_condition.n               -0.019977473
land_surface_condition.t                0.024239911
foundation_type.r                       0.008660952
foundation_type.u                      -0.036727795
foundation_type.w                      -0.106852148
roof_type.n                            -0.126140119
roof_type.q                             0.039479960
roof_type.x                             0.169657178
ground_floor_type.f                    -0.052502025
ground_floor_type.v                     0.062000623
ground_floor_type.x                     0.014228684
other_floor_type.j                     -0.531358470
other_floor_type.q                      0.202726528
other_floor_type.x                      0.078891061
position.j                              0.229006959
position.s                             -0.216106678
position.t                              0.067331070
has_superstructure_adobe_mud            0.149725170
has_superstructure_mud_mortar_stone    -0.106572989
has_superstructure_mud_mortar_brick     0.209097769
has_superstructure_cement_mortar_brick  0.001697751
has_superstructure_timber              -0.052402476
has_superstructure_bamboo              -0.063341882
count_families                          0.064316081
has_secondary_use                       0.091779891
has_secondary_use_agriculture          -0.005390015
                                       land_surface_condition.n
geo_level_1_id                         -0.028659774
geo_level_2_id                          0.033524081
geo_level_3_id                          0.012012545
count_floors_pre_eq                    -0.038525062
age                                    -0.012086677
area_percentage                        -0.028422431
height_percentage                      -0.019977473
land_surface_condition.n                1.000000000
land_surface_condition.t               -0.883395457
foundation_type.r                       0.026637757
foundation_type.u                      -0.020409532
foundation_type.w                       0.003250465
roof_type.n                             0.043577087
roof_type.q                            -0.023711482
roof_type.x                            -0.040881050
ground_floor_type.f                     0.028089964
ground_floor_type.v                    -0.050064449
ground_floor_type.x                     0.005384728
other_floor_type.j                     -0.001641842
other_floor_type.q                     -0.018645601
other_floor_type.x                      0.042294585
position.j                             -0.030546488
position.s                              0.024974137
position.t                             -0.004253791
has_superstructure_adobe_mud           -0.005326544
has_superstructure_mud_mortar_stone     0.074832008
has_superstructure_mud_mortar_brick    -0.050381906
has_superstructure_cement_mortar_brick -0.054304164
has_superstructure_timber               0.034529749
has_superstructure_bamboo               0.022884006
count_families                         -0.008839824
has_secondary_use                      -0.005813440
has_secondary_use_agriculture           0.005457553
                                       land_surface_condition.t
geo_level_1_id                          0.0303373733
geo_level_2_id                         -0.0331909305
geo_level_3_id                         -0.0180251737
count_floors_pre_eq                     0.0462183437
age                                     0.0184340079
area_percentage                         0.0258172259
height_percentage                       0.0242399106
land_surface_condition.n               -0.8833954570
land_surface_condition.t                1.0000000000
foundation_type.r                      -0.0233757330
foundation_type.u                       0.0254890693
foundation_type.w                      -0.0138891880
roof_type.n                            -0.0471996922
roof_type.q                             0.0250812342
roof_type.x                             0.0453381294
ground_floor_type.f                    -0.0286855026
ground_floor_type.v                     0.0568635193
ground_floor_type.x                    -0.0118217209
other_floor_type.j                      0.0008055381
other_floor_type.q                      0.0210709055
other_floor_type.x                     -0.0449482936
position.j                              0.0359881662
position.s                             -0.0311472654
position.t                              0.0069406197
has_superstructure_adobe_mud            0.0140951585
has_superstructure_mud_mortar_stone    -0.0796433887
has_superstructure_mud_mortar_brick     0.0629754548
has_superstructure_cement_mortar_brick  0.0598024340
has_superstructure_timber              -0.0452422845
has_superstructure_bamboo              -0.0308132143
count_families                          0.0084400621
has_secondary_use                       0.0016355700
has_secondary_use_agriculture          -0.0065372153
                                       foundation_type.r foundation_type.u
geo_level_1_id                         -0.188060656       0.077188739
geo_level_2_id                          0.097980438      -0.062513597
geo_level_3_id                          0.001455932      -0.007069158
count_floors_pre_eq                     0.131691925      -0.095874163
age                                     0.072639710      -0.020130954
area_percentage                        -0.198505861       0.126860116
height_percentage                       0.008660952      -0.036727795
land_surface_condition.n                0.026637757      -0.020409532
land_surface_condition.t               -0.023375733       0.025489069
foundation_type.r                       1.000000000      -0.553581197
foundation_type.u                      -0.553581197       1.000000000
foundation_type.w                      -0.570987206      -0.059707360
roof_type.n                             0.260968541      -0.083819350
roof_type.q                            -0.006366217      -0.036398386
roof_type.x                            -0.483566431       0.222982406
ground_floor_type.f                     0.385112150      -0.306078185
ground_floor_type.v                    -0.514299786       0.338506911
ground_floor_type.x                     0.005984312       0.073192786
other_floor_type.j                     -0.202061762       0.149500137
other_floor_type.q                      0.325542358      -0.168047131
other_floor_type.x                      0.008311691      -0.034649958
position.j                             -0.067187583       0.037070329
position.s                              0.038126794      -0.038384789
position.t                             -0.004205432       0.019644132
has_superstructure_adobe_mud            0.098100560      -0.051292543
has_superstructure_mud_mortar_stone     0.538937022      -0.260836024
has_superstructure_mud_mortar_brick     0.071138734      -0.016662386
has_superstructure_cement_mortar_brick -0.405372425       0.432362361
has_superstructure_timber              -0.126081927      -0.048160788
has_superstructure_bamboo              -0.136060826      -0.039398532
count_families                          0.034281016      -0.014279986
has_secondary_use                      -0.106780588       0.035893793
has_secondary_use_agriculture           0.038260891      -0.030319536
                                       foundation_type.w roof_type.n
geo_level_1_id                          0.212048338      -0.0274540269
geo_level_2_id                         -0.042830629       0.0828019233
geo_level_3_id                          0.010620525       0.0020520653
count_floors_pre_eq                    -0.133956351      -0.0992781621
age                                    -0.051183992       0.0225041670
area_percentage                        -0.064849187      -0.1487601691
height_percentage                      -0.106852148      -0.1261401189
land_surface_condition.n                0.003250465       0.0435770869
land_surface_condition.t               -0.013889188      -0.0471996922
foundation_type.r                      -0.570987206       0.2609685407
foundation_type.u                      -0.059707360      -0.0838193499
foundation_type.w                       1.000000000      -0.0915213107
roof_type.n                            -0.091521311       1.0000000000
roof_type.q                             0.134854472      -0.8529323146
roof_type.x                            -0.063855658      -0.3945713722
ground_floor_type.f                     0.043100587       0.1896579908
ground_floor_type.v                    -0.020196591      -0.2536800458
ground_floor_type.x                    -0.052854820      -0.0057970743
other_floor_type.j                      0.086418627       0.0458501323
other_floor_type.q                     -0.101437724       0.0512692125
other_floor_type.x                      0.078369389       0.0435648447
position.j                             -0.039820369      -0.0441914113
position.s                              0.082232723       0.0430777357
position.t                             -0.063986631      -0.0238725073
has_superstructure_adobe_mud           -0.057067382       0.0671846082
has_superstructure_mud_mortar_stone    -0.251561638       0.1849094952
has_superstructure_mud_mortar_brick    -0.054542182       0.0232481966
has_superstructure_cement_mortar_brick  0.003676782      -0.1541818639
has_superstructure_timber               0.321597695       0.0005882939
has_superstructure_bamboo               0.298215373      -0.0237441301
count_families                         -0.016648387      -0.0130921793
has_secondary_use                      -0.009915079      -0.0297274930
has_secondary_use_agriculture           0.005800972       0.0450717865
                                       roof_type.q  roof_type.x
geo_level_1_id                          0.002146344  0.048272296
geo_level_2_id                         -0.051035486 -0.067151852
geo_level_3_id                          0.006103992 -0.014634808
count_floors_pre_eq                     0.085248635  0.038167098
age                                    -0.001465003 -0.040087118
area_percentage                        -0.043029800  0.357776863
height_percentage                       0.039479960  0.169657178
land_surface_condition.n               -0.023711482 -0.040881050
land_surface_condition.t                0.025081234  0.045338129
foundation_type.r                      -0.006366217 -0.483566431
foundation_type.u                      -0.036398386  0.222982406
foundation_type.w                       0.134854472 -0.063855658
roof_type.n                            -0.852932315 -0.394571372
roof_type.q                             1.000000000 -0.143124784
roof_type.x                            -0.143124784  1.000000000
ground_floor_type.f                     0.072146240 -0.486566286
ground_floor_type.v                    -0.103696115  0.663480469
ground_floor_type.x                     0.008144731 -0.003345685
other_floor_type.j                     -0.113586939  0.113008765
other_floor_type.q                      0.122345705 -0.312555314
other_floor_type.x                      0.012236586 -0.104133838
position.j                             -0.037965051  0.150609142
position.s                              0.036829249 -0.146498471
position.t                             -0.013243545  0.068571437
has_superstructure_adobe_mud           -0.042599753 -0.052391490
has_superstructure_mud_mortar_stone     0.049611422 -0.437897659
has_superstructure_mud_mortar_brick    -0.034398209  0.016471490
has_superstructure_cement_mortar_brick -0.072475351  0.419886124
has_superstructure_timber               0.073468618 -0.130435237
has_superstructure_bamboo               0.067671526 -0.074099131
count_families                          0.028032533 -0.024521462
has_secondary_use                      -0.056887125  0.156493631
has_secondary_use_agriculture          -0.017782795 -0.054150572
                                       ground_floor_type.f ground_floor_type.v
geo_level_1_id                         -0.075405167         0.110562502
geo_level_2_id                          0.099326649        -0.078278885
geo_level_3_id                          0.008915848        -0.004324925
count_floors_pre_eq                     0.057356319        -0.070247038
age                                     0.043667780        -0.052341946
area_percentage                        -0.258259122         0.328150406
height_percentage                      -0.052502025         0.062000623
land_surface_condition.n                0.028089964        -0.050064449
land_surface_condition.t               -0.028685503         0.056863519
foundation_type.r                       0.385112150        -0.514299786

In [129]:
X <- cbind(matrix(1, nr = 260601, nc = 1),X)

In [80]:
dim(Y)

[1] 260601      3

In [79]:
dim(t(X))

[1]     34 260601

In [76]:
dim(t(X)%*%X)

[1] 34 34

In [77]:
solve(t(X)%*%X)

ERROR: Error in solve.default(t(X) %*% X): le système est numériquement singulier : conditionnement de la réciproque = 3.76789e-25

In [65]:
beta_hat <- solve(t(X)%*%X)%*%t(X)%*%Y

ERROR: Error in solve.default(t(X) %*% X): le système est numériquement singulier : conditionnement de la réciproque = 3.76789e-25

In [51]:
test <- as.matrix(test)

In [52]:
test[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 17             596            11307          3                   20
2  6             141            11987          2                   25
  area_percentage height_percentage land_surface_condition.n
1  7              6                 0
2 13              5                 0
  land_surface_condition.t foundation_type.r foundation_type.u
1 1                        1                 0
2 1                        1                 0
  foundation_type.w roof_type.n roof_type.q roof_type.x ground_floor_type.f
1 0                 1           0           0           1
2 0                 1           0           0           1
  ground_floor_type.v ground_floor_type.x other_floor_type.j other_floor_type.q
1 0                   0                   0                  1
2 0                   0                   0                  1
  other_floor_type.x position.j position.s position.t
1 0                  0          1          0
2 0                  0          1          0
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo count_families
1 0                         0                         1
2 0                         0                         1
  has_secondary_use has_secondary_use_agriculture
1 0                 0
2 1                 1

In [53]:
dim(beta_hat)

[1] 33  3

In [54]:
dim(test)

[1] 86868    33

In [58]:
dim(X)

[1] 260601     33

In [61]:
X <- cbind(matrix(1, nr = 260601, nc = 1),X)

In [81]:
?svd

In [130]:
X <- X[,-info$remove]
test <- test[,-info$remove]

apres avoir enlever la dependence linéaire on peux inverser cette matrice

In [101]:
solve(t(X)%*%X)

                                                     geo_level_1_id
                                        1.734044e-03 -5.152794e-07
geo_level_1_id                         -5.152794e-07  6.551156e-08
geo_level_2_id                         -1.363644e-08  4.319825e-11
geo_level_3_id                         -1.679408e-09 -3.657677e-13
count_floors_pre_eq                    -4.617279e-05 -5.570774e-09
age                                    -2.611054e-08 -1.012952e-10
area_percentage                        -2.022500e-06 -7.437049e-09
height_percentage                      -8.178059e-06  3.000418e-09
land_surface_condition.n               -1.237604e-04 -6.787722e-09
land_surface_condition.t               -1.201970e-04 -4.439765e-08
foundation_type.r                      -7.338384e-05 -1.597372e-07
foundation_type.u                      -6.283565e-05 -1.720954e-07
foundation_type.w                      -8.943115e-05 -5.123175e-07
roof_type.n                            -5.344369e-05 -8.218576e-11
roof_type.q                            -4.554746e-05  1.989224e-08
ground_floor_type.f                    -6.534320e-04 -8.867308e-08
ground_floor_type.v                    -7.195840e-04 -1.979873e-07
ground_floor_type.x                    -6.614751e-04 -8.142162e-08
other_floor_type.j                     -1.832337e-04 -1.332612e-07
other_floor_type.q                     -1.037341e-04 -3.257775e-08
other_floor_type.x                     -1.077301e-04 -8.223590e-08
position.j                             -4.908119e-04 -1.287517e-10
position.s                             -5.283122e-04 -7.752040e-09
position.t                             -5.249674e-04  3.153248e-09
has_superstructure_adobe_mud            4.572245e-06  2.592514e-08
has_superstructure_mud_mortar_stone     1.159611e-06  9.226028e-08
has_superstructure_mud_mortar_brick    -6.354291e-06  1.060521e-07
has_superstructure_cement_mortar_brick -1.646098e-05 -1.189175e-07
has_superstructure_timber              -6.575755e-06 -1.245379e-07
has_superstructure_bamboo               1.361758e-06  3.636428e-08
count_families                         -1.451409e-05 -4.718718e-08
has_secondary_use                      -3.542688e-05  4.482131e-08
has_secondary_use_agriculture           2.947770e-05 -2.378524e-08
                                       geo_level_2_id geo_level_3_id
                                       -1.363644e-08  -1.679408e-09
geo_level_1_id                          4.319825e-11  -3.657677e-13
geo_level_2_id                          2.311225e-11  -1.279040e-15
geo_level_3_id                         -1.279040e-15   2.893369e-13
count_floors_pre_eq                    -3.899282e-10  -3.544763e-12
age                                    -3.086844e-13   3.090182e-14
area_percentage                         4.623533e-11  -7.186215e-13
height_percentage                      -1.773387e-10   8.797157e-12
land_surface_condition.n               -3.918969e-10   5.376253e-11
land_surface_condition.t                4.175868e-10   8.811053e-11
foundation_type.r                      -1.223980e-09   4.176330e-11
foundation_type.u                      -3.483187e-11   5.422541e-11
foundation_type.w                      -7.174593e-10  -3.214835e-11
roof_type.n                            -6.710548e-10  -6.427000e-11
roof_type.q                             6.780343e-10  -7.609686e-11
ground_floor_type.f                    -9.380320e-11  -3.288265e-11
ground_floor_type.v                     5.708209e-10  -7.772537e-11
ground_floor_type.x                     1.737555e-09  -1.974409e-11
other_floor_type.j                     -7.033740e-10  -1.291050e-12
other_floor_type.q                     -3.530867e-10   1.122576e-11
other_floor_type.x                      3.758883e-10   1.276484e-11
position.j                             -2.029324e-10  -1.064291e-10
position.s                             -4.811202e-10  -1.312958e-10
position.t                             -6.570962e-10  -1.227005e-10
has_superstructure_adobe_mud           -9.711900e-11  -6.197867e-12
has_superstructure_mud_mortar_stone    -5.354347e-10  -7.910800e-11
has_superstructure_mud_mortar_brick    -4.335651e-10   6.609399e-12
has_superstructure_cement_mortar_brick  7.850760e-10  -3.545003e-11
has_superstructure_timber               6.661187e-11   2.990474e-11
has_superstructure_bamboo               8.631247e-10  -2.475991e-11
count_families                          3.039477e-10   1.138038e-12
has_secondary_use                      -1.232196e-10   2.843192e-12
has_secondary_use_agriculture          -1.637062e-10  -6.512684e-11
                                       count_floors_pre_eq age
                                       -4.617279e-05       -2.611054e-08
geo_level_1_id                         -5.570774e-09       -1.012952e-10
geo_level_2_id                         -3.899282e-10       -3.086844e-13
geo_level_3_id                         -3.544763e-12        3.090182e-14
count_floors_pre_eq                     2.625602e-05       -2.856999e-09
age                                    -2.856999e-09        7.246671e-10
area_percentage                         6.994427e-08       -1.029010e-10
height_percentage                      -5.232720e-06       -1.353307e-10
land_surface_condition.n               -2.088088e-08       -2.213185e-09
land_surface_condition.t               -1.019844e-06       -3.693819e-09
foundation_type.r                      -9.735567e-07       -8.577720e-09
foundation_type.u                       6.886314e-07       -7.315960e-09
foundation_type.w                       1.977280e-06        3.090478e-09
roof_type.n                             1.571157e-06       -9.383693e-10
roof_type.q                             6.764687e-08       -5.084077e-10
ground_floor_type.f                    -1.758575e-06        1.203820e-09
ground_floor_type.v                     3.262212e-07        5.119119e-09
ground_floor_type.x                    -9.061172e-07        3.691379e-09
other_floor_type.j                      1.582709e-05       -2.427086e-09
other_floor_type.q                     -3.600756e-06       -3.525230e-09
other_floor_type.x                     -2.040893e-06       -1.404662e-09
position.j                              1.375232e-05        1.846896e-08
position.s                              2.207637e-05        2.903067e-08
position.t                              2.122611e-05        2.791946e-08
has_superstructure_adobe_mud           -7.911785e-07       -5.212583e-09
has_superstructure_mud_mortar_stone     8.953013e-07        1.111025e-09
has_superstructure_mud_mortar_brick    -5.273621e-06       -6.204063e-09
has_superstructure_cement_mortar_brick -3.832543e-07        3.421866e-09
has_superstructure_timber               8.603717e-07       -2.344925e-09
has_superstructure_bamboo               6.238466e-07        5.185373e-10
count_families                         -1.168740e-06        7.843843e-10
has_secondary_use                      -1.001962e-06        1.074714e-09
has_secondary_use_agriculture           1.620253e-06       -3.645831e-10
                                       area_percentage height_percentage
                                       -2.022500e-06   -8.178059e-06
geo_level_1_id                         -7.437049e-09    3.000418e-09
geo_level_2_id                          4.623533e-11   -1.773387e-10
geo_level_3_id                         -7.186215e-13    8.797157e-12
count_floors_pre_eq                     6.994427e-08   -5.232720e-06
age                                    -1.029010e-10   -1.353307e-10
area_percentage                         2.471367e-07   -8.190313e-08
height_percentage                      -8.190313e-08    2.879849e-06
land_surface_condition.n                7.527799e-08   -2.840913e-08
land_surface_condition.t                5.499334e-08    1.924097e-07
foundation_type.r                       2.008945e-07    7.780638e-07
foundation_type.u                       8.443719e-08    6.475372e-07
foundation_type.w                       4.722631e-07    5.875731e-07
roof_type.n                             7.793219e-07    1.965759e-07
roof_type.q                             7.648529e-07    2.156992e-07
ground_floor_type.f                     1.479546e-07    2.867190e-07
ground_floor_type.v                    -3.310770e-07    1.606152e-07
ground_floor_type.x                     4.694787e-08    3.015909e-08
other_floor_type.j                      2.633035e-07    4.384247e-06
other_floor_type.q                      1.278613e-07    3.460385e-06
other_floor_type.x                      6.529477e-09    3.109330e-06
position.j                             -3.851335e-07   -6.497026e-07
position.s                             -6.145673e-07   -2.136277e-07
position.t                             -5.102558e-07   -4.013336e-07
has_superstructure_adobe_mud           -8.693813e-08   -4.925048e-07
has_superstructure_mud_mortar_stone     9.048811e-08   -6.401146e-09
has_superstructure_mud_mortar_brick    -1.291366e-07   -3.084262e-07
has_superstructure_cement_mortar_brick -5.713621e-08    7.002032e-08
has_superstructure_timber               2.693690e-08   -7.352803e-08
has_superstructure_bamboo              -6.722396e-08    6.146346e-08
count_families                         -2.329170e-07    3.080955e-08
has_secondary_use                      -4.026635e-07   -3.894827e-07
has_secondary_use_agriculture           3.295024e-07    2.307321e-07
                                       land_surface_condition.n
                                       -1.237604e-04
geo_level_1_id                         -6.787722e-09
geo_level_2_id                         -3.918969e-10
geo_level_3_id                          5.376253e-11
count_floors_pre_eq                    -2.088088e-08
age                                    -2.213185e-09
area_percentage                         7.527799e-08
height_percentage                      -2.840913e-08
land_surface_condition.n                1.486756e-04
land_surface_condition.t                1.204832e-04
foundation_type.r                       1.827574e-07
foundation_type.u                      -8.211470e-07
foundation_type.w                       1.123561e-06
roof_type.n                             8.945648e-07
roof_type.q                             8.536402e-07
ground_floor_type.f                     3.974457e-06
ground_floor_type.v                     2.753306e-06
ground_floor_type.x                     4.769009e-06
other_floor_type.j                     -8.240967e-07
other_floor_type.q                     -6.037675e-07
other_floor_type.x                     -1.186634e-06
position.j                             -2.973487e-07
position.s                             -1.204074e-07
position.t                             -2.930197e-07
has_superstructure_adobe_mud           -1.622283e-06
has_superstructure_mud_mortar_stone    -1.550300e-06
has_superstructure_mud_mortar_brick    -1.434601e-06
has_superstructure_cement_mortar_brick -1.733651e-08
has_superstructure_timber               3.953350e-07
has_superstructure_bamboo               1.047973e-07
count_families                          1.531182e-07
has_secondary_use                       1.476587e-06
has_secondary_use_agriculture          -1.369863e-06
                                       land_surface_condition.t
                                       -1.201970e-04
geo_level_1_id                         -4.439765e-08
geo_level_2_id                          4.175868e-10
geo_level_3_id                          8.811053e-11
count_floors_pre_eq                    -1.019844e-06
age                                    -3.693819e-09
area_percentage                         5.499334e-08
height_percentage                       1.924097e-07
land_surface_condition.n                1.204832e-04
land_surface_condition.t                1.256109e-04
foundation_type.r                      -1.285485e-07
foundation_type.u                      -5.816779e-07
foundation_type.w                       1.422074e-06
roof_type.n                             1.143046e-06
roof_type.q                             3.757235e-07
ground_floor_type.f                     1.459845e-08
ground_floor_type.v                    -1.708868e-06
ground_floor_type.x                     1.198572e-06
other_floor_type.j                     -1.856628e-06
other_floor_type.q                     -1.848335e-06
other_floor_type.x                     -1.069181e-06
position.j                             -2.726463e-07
position.s                              1.774778e-07
position.t                              2.820549e-08
has_superstructure_adobe_mud           -4.935989e-07
has_superstructure_mud_mortar_stone     4.551113e-07
has_superstructure_mud_mortar_brick    -2.473749e-06
has_superstructure_cement_mortar_brick -9.769695e-07
has_superstructure_timber               1.134211e-06
has_superstructure_bamboo               6.578585e-07
count_families                          7.158753e-08
has_secondary_use                       1.668270e-06
has_secondary_use_agriculture          -1.636730e-06
                                       foundation_type.r foundation_type.u
                                       -7.338384e-05     -6.283565e-05
geo_level_1_id                         -1.597372e-07     -1.720954e-07
geo_level_2_id                         -1.223980e-09     -3.483187e-11
geo_level_3_id                          4.176330e-11      5.422541e-11
count_floors_pre_eq                    -9.735567e-07      6.886314e-07
age                                    -8.577720e-09     -7.315960e-09
area_percentage                         2.008945e-07      8.443719e-08
height_percentage                       7.780638e-07      6.475372e-07
land_surface_condition.n                1.827574e-07     -8.211470e-07
land_surface_condition.t               -1.285485e-07     -5.816779e-07
foundation_type.r                       2.129129e-04      1.583256e-04
foundation_type.u                       1.583256e-04      2.131616e-04
foundation_type.w                       1.925606e-04      1.538545e-04
roof_type.n                            -7.125593e-05     -5.870814e-05
roof_type.q                            -7.090512e-05     -5.900432e-05
ground_floor_type.f                    -7.746452e-06     -3.305245e-06
ground_floor_type.v                     2.510560e-05      1.170476e-05
ground_floor_type.x                    -5.605799e-06     -6.482637e-06
other_floor_type.j                     -2.803547e-05     -2.046944e-05
other_floor_type.q                     -3.430556e-05     -2.530559e-05
other_floor_type.x                     -3.381108e-05     -2.431521e-05
position.j                              2.258721e-06      1.008107e-06
position.s                              1.364302e-07     -5.211414e-07
position.t                              8.555193e-07     -2.069913e-07
has_superstructure_adobe_mud           -9.951201e-06     -3.040427e-06
has_superstructure_mud_mortar_stone    -2.576380e-05     -1.165197e-05
has_superstructure_mud_mortar_brick    -2.424917e-05     -1.317603e-05
has_superstructure_cement_mortar_brick -2.108717e-05     -4.085133e-05
has_superstructure_timber               1.387540e-06      1.175411e-06
has_superstructure_bamboo               1.311525e-07     -3.635645e-07
count_families                         -7.331973e-07     -3.279414e-07
has_secondary_use                       8.567953e-06      7.894427e-06
has_secondary_use_agriculture          -8.690927e-06     -7.820054e-06
                                       foundation_type.w roof_type.n
                                       -8.943115e-05     -5.344369e-05
geo_level_1_id                         -5.123175e-07     -8.218576e-11
geo_level_2_id                         -7.174593e-10     -6.710548e-10
geo_level_3_id                         -3.214835e-11     -6.427000e-11
count_floors_pre_eq                     1.977280e-06      1.571157e-06
age                                     3.090478e-09     -9.383693e-10
area_percentage                         4.722631e-07      7.793219e-07
height_percentage                       5.875731e-07      1.965759e-07
land_surface_condition.n                1.123561e-06      8.945648e-07
land_surface_condition.t                1.422074e-06      1.143046e-06
foundation_type.r                       1.925606e-04     -7.125593e-05
foundation_type.u                       1.538545e-04     -5.870814e-05
foundation_type.w                       2.773456e-04     -7.404993e-05
roof_type.n                            -7.404993e-05      2.036677e-04
roof_type.q                            -7.889115e-05      1.993978e-04
ground_floor_type.f                    -3.062907e-06      2.700233e-06
ground_floor_type.v                     3.487016e-05      3.556279e-05
ground_floor_type.x                     2.625370e-06      5.528486e-06
other_floor_type.j                     -2.447895e-05     -7.288736e-05
other_floor_type.q                     -3.266482e-05     -8.195459e-05
other_floor_type.x                     -3.366034e-05     -8.479535e-05
position.j                              1.100306e-06     -5.188924e-07
position.s                             -3.389029e-06     -3.302150e-06
position.t                             -8.988569e-08     -1.753453e-06
has_superstructure_adobe_mud            4.960698e-06     -3.431869e-06
has_superstructure_mud_mortar_stone     5.737430e-06     -5.082745e-06
has_superstructure_mud_mortar_brick    -7.736673e-06      1.734408e-07
has_superstructure_cement_mortar_brick -1.295840e-05      5.606081e-06
has_superstructure_timber              -7.968151e-06     -3.153352e-06
has_superstructure_bamboo              -1.282691e-05      4.172056e-07
count_families                         -1.189160e-07     -1.250328e-06
has_secondary_use                       7.321563e-06     -1.449835e-06
has_secondary_use_agriculture          -8.367167e-06      3.387127e-07
                                       roof_type.q   ground_floor_type.f
                                       -4.554746e-05 -6.534320e-04
geo_level_1_id                          1.989224e-08 -8.867308e-08
geo_level_2_id                          6.780343e-10 -9.380320e-11
geo_level_3_id                         -7.609686e-11 -3.288265e-11
count_floors_pre_eq                     6.764687e-08 -1.758575e-06
age                                    -5.084077e-10  1.203820e-09
area_percentage                         7.648529e-07  1.479546e-07
height_percentage                       2.156992e-07  2.867190e-07
land_surface_condition.n                8.536402e-07  3.974457e-06
land_surface_condition.t                3.757235e-07  1.459845e-08
foundation_type.r                      -7.090512e-05 -7.746452e-06
foundation_type.u                      -5.900432e-05 -3.305245e-06
foundation_type.w                      -7.889115e-05 -3.062907e-06
roof_type.n                             1.993978e-04  2.700233e-06
roof_type.q                             2.179347e-04  1.521175e-06
ground_floor_type.f                     1.521175e-06  6.800610e-04
ground_floor_type.v                     3.408544e-05  6.565224e-04
ground_floor_type.x                     3.830639e-06  6.727007e-04
other_floor_type.j                     -7.422254e-05  3.785727e-06
other_floor_type.q                     -8.524070e-05 -3.819637e-07
other_floor_type.x                     -8.710542e-05  3.651787e-06
position.j                             -2.702092e-06  1.562580e-06
position.s                             -6.609280e-06 -1.575986e-07
position.t                             -5.039219e-06  1.871213e-08
has_superstructure_adobe_mud           -1.443553e-06 -8.451618e-06
has_superstructure_mud_mortar_stone    -4.261190e-06 -1.580406e-05
has_superstructure_mud_mortar_brick     1.701106e-06 -5.451351e-06
has_superstructure_cement_mortar_brick  5.871300e-06  1.535277e-07
has_superstructure_timber              -3.491130e-06  2.073306e-06
has_superstructure_bamboo              -2.982771e-07 -6.471132e-06

In [131]:
beta_hat <- solve(t(X)%*%X)%*%t(X)%*%Y

In [113]:
beta_hat <- as.matrix(beta_hat)

In [132]:
dim(test)
dim(matrix(1, nr = 86868, nc = 1))
dim(beta_hat)

[1] 86868    32

[1] 86868     1

[1] 33  3

In [133]:
test <- cbind(matrix(1, nr = 86868, nc = 1),test)

In [210]:
solution <- test %*% beta_hat

In [211]:
solution

      damage_grade.1 damage_grade.2 damage_grade.3
1      -8.28149590   -26.6181268    35.8996227
2      -1.79604112    -4.5980749     7.3941160
3      -0.10689505     0.7257480     0.3811470
4       0.05872397    -0.1546930     1.0959691
5      -3.87511800   -12.1125251    16.9876431
6      -2.31955877    -6.9369172    10.2564760
7      -5.66336351   -19.0661470    25.7295105
8     -19.27631040   -64.3756563    84.6519667
9      -3.28481145   -10.3236741    14.6084856
10    -10.54562357   -34.9221665    46.4677901
11     -2.72992086    -9.2826591    13.0125800
12     -4.90165308   -15.7276902    21.6293433
13     -6.50121462   -20.3870450    27.8882596
14     -7.31424115   -24.0774991    32.3917403
15    -13.87691142   -46.3205041    61.1974155
16    -12.84828455   -41.7966863    55.6449708
17    -17.20039919   -56.2910773    74.4914765
18     -1.33207671    -3.5983961     5.9304728
19     -3.28901887   -10.4470272    14.7360461
20    -14.40260779   -47.5008549    62.9034627
21    -19.37626213   -64.3253052    84.7015673
22    -16.21677386   -53.2546212    70.4713951
23    -17.66105402   -58.1811731    76.8422271
24    -17.25498207   -56.8621148    75.1170969
25     -8.91098909   -29.7249523    39.6359414
26     -7.18390572   -23.4585103    31.6424160
27    -16.73659756   -55.6709381    73.4075356
28     -2.38404596    -6.6352655    10.0193115
29    -10.37411498   -34.2873670    45.6614819
30     -0.03679299     0.1927537     0.8440393
⋮     ⋮              ⋮              ⋮
86839  -7.10226808   -23.07930536   31.1815734
86840  -2.81962226    -9.12329496   12.9429172
86841 -18.09485409   -59.67759035   78.7724444
86842 -18.36612948   -61.10558842   80.4717179
86843  -1.90316503    -6.27847474    9.1816398
86844 -10.39456029   -34.82468578   46.2192461
86845 -15.79554155   -52.28987190   69.0854135
86846 -19.38315956   -64.54078438   84.9239439
86847  -4.97516705   -15.84458909   21.8197561
86848  -4.17756214   -13.12891244   18.3064746
86849 -10.84880595   -35.51773882   47.3665448
86850  -0.24058673    -0.21084989    1.4514366
86851 -16.80083131   -55.08588757   72.8867189
86852  -0.44915204    -2.36367474    3.8128268
86853 -10.94404695   -36.37695540   48.3210024
86854 -13.37426429   -44.28965756   58.6639219
86855  -5.56046487   -18.00832025   24.5687851
86856  -5.90402070   -18.83879692   25.7428176
86857 -19.62265426   -64.59445712   85.2171114
86858 -13.95442540   -46.29212078   61.2465462
86859 -16.11382677   -53.24125272   70.3550795
86860  -0.53617285    -1.17745691    2.7136298
86861  -2.09214919    -6.94385776   10.0360069
86862  -6.05488871   -20.04395019   27.0988389
86863 -15.87335337   -54.20539584   71.0787492
86864  -8.31604325   -26.87067607   36.1867193
86865 -19.90061874   -65.30155370   86.2021724
86866 -16.06467783   -52.84160692   69.9062848
86867 -14.57447260   -48.22038595   63.7948586
86868  -0.03103712     0.09832591    0.9327112

In [197]:
sol <- as.data.frame(solution)

In [145]:
sol[1:2,]

  damage_grade.1 damage_grade.2 damage_grade.3
1 -8.281496      -26.618127     35.899623
2 -1.796041       -4.598075      7.394116

In [146]:
typeof(sol)

[1] "list"

In [148]:
??NumPy

In [149]:
?argmax

In [157]:
?which.max

In [152]:
a <- c(1,0,0,0)

In [153]:
typeof(a)

[1] "double"

In [154]:
a <- list(a)

In [155]:
typeof(a)

[1] "list"

In [156]:
which.max(a)

ERROR: Error in which.max(a): l'objet 'list' ne peut être converti automatiquement en un type 'double'

In [206]:
typeof(solution)

[1] "double"

In [233]:
dim(solution)

[1] 86868     3

In [243]:
a <-matrix(0, nrow = nr, ncol = 3)
a

     [,1] [,2] [,3]
[1,] 0    0    0
[2,] 0    0    0

In [241]:
a[1,] <- tabulate(1, nbins = 4)

In [242]:
a

     [,1] [,2] [,3] [,4]
[1,] 1    0    0    0
[2,] 0    0    0    0

In [247]:
a <- which.max(solution[1,])
typeof(a)

[1] "integer"

In [181]:
sol[1,]

  damage_grade.1 damage_grade.2 damage_grade.3
1 -8.281496      -26.61813      35.89962

In [ ]:
data[39] <- lapply(data[39], function(x) as.character(x))

In [198]:
sol <- lapply(sol, function(x) unlist(x))

In [205]:
length(sol)

[1] 3

In [208]:
solution1 <- sapply(solution, function(x) which.max(x))

In [190]:
a

[[1]]
[1] 1 1

[[2]]
[1] 1 1

In [191]:
a <- list(a)

In [192]:
a

[[1]]
[[1]][[1]]
[1] 1 1

[[1]][[2]]
[1] 1 1

In [193]:
unlist(a)

[1] 1 1 1 1

In [220]:
typeof(nrow(solution))

[1] "integer"

In [221]:
for (i in 1:3){print(i)}

[1] 1
[1] 2
[1] 3

In [223]:
y <- numeric(nrow(solution))
for (i in 1:nrow(solution)){y[i] <- which.max(solution[i,])}

In [225]:
y <- as.data.frame(y)

In [226]:
y

      y
1     3
2     3
3     2
4     3
5     3
6     3
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16    3
17    3
18    3
19    3
20    3
21    3
22    3
23    3
24    3
25    3
26    3
27    3
28    3
29    3
30    3
⋮     ⋮
86839 3
86840 3
86841 3
86842 3
86843 3
86844 3
86845 3
86846 3
86847 3
86848 3
86849 3
86850 3
86851 3
86852 3
86853 3
86854 3
86855 3
86856 3
86857 3
86858 3
86859 3
86860 3
86861 3
86862 3
86863 3
86864 3
86865 3
86866 3
86867 3
86868 3