## Data pre-procesing

On commence par importer notre data.

In [1]:
train_values <- read.csv("train_values.csv",stringsAsFactors = T)
test_values <- read.csv("test_values.csv",stringsAsFactors = T)
train_labels <- read.csv("train_labels.csv",stringsAsFactors = T)
submission_format <- read.csv("submission_format.csv",stringsAsFactors = T)

On voudrait merge train_values et train_labels par leur colone id_building.

Voir : https://stackoverflow.com/questions/31429736/how-to-join-data-from-2-different-csv-files-in-r

In [4]:
#?merge

In [2]:
data <- merge(train_values,train_labels,by=c('building_id','building_id'),all.x=T)

On s'assurer que le fusion a bien été éffectuer.

In [6]:
dim(data)

[1] 260601     40

In [7]:
options(repr.matrix.max.cols=50)
data[1:2,]

  building_id geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq
1 4           30             266             1224          1
2 8           17             409            12182          2
  age area_percentage height_percentage land_surface_condition foundation_type
1 25   5              2                 t                      r
2  0  13              7                 t                      r
  roof_type ground_floor_type other_floor_type position plan_configuration
1 n         f                 j                s        d
2 n         f                 q                s        d
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status count_families
1 0                        v                      0
2 0                        v                      1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade
1 0                            0                       2
2 0                            0                       3

On va maintenant suprimer la colone building_id, qui n'apporte pas d'information suplemetaire.

In [3]:
data <- data[,-1]

On vérifie que l'operation ses bien effectuer.

In [20]:
options(repr.matrix.max.cols=50)
data[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 30             266             1224          1                   25
2 17             409            12182          2                    0
  area_percentage height_percentage land_surface_condition foundation_type
1  5              2                 t                      r
2 13              7                 t                      r
  roof_type ground_floor_type other_floor_type position plan_configuration
1 n         f                 j                s        d
2 n         f                 q                s        d
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status count_families
1 0                        v                      0
2 0                        v                      1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade
1 0                            0                       2
2 0                            0                       3

Vérifion maintenant qu'il n'y a pas de valeur manquante.

Pour ça on puex commencer par regarder le résumer de notre data, pour voir le nombre de valeur NA et si il n'y a pas de caractére vide.

In [24]:
summary(data,maxsum = 11) # maxsum = 11 permet d'afficher jusqu'a 11 valeur pour les facteur

 geo_level_1_id geo_level_2_id   geo_level_3_id  count_floors_pre_eq
 Min.   : 0.0   Min.   :   0.0   Min.   :    0   Min.   :1.00
 1st Qu.: 7.0   1st Qu.: 350.0   1st Qu.: 3073   1st Qu.:2.00
 Median :12.0   Median : 702.0   Median : 6270   Median :2.00
 Mean   :13.9   Mean   : 701.1   Mean   : 6258   Mean   :2.13
 3rd Qu.:21.0   3rd Qu.:1050.0   3rd Qu.: 9412   3rd Qu.:2.00
 Max.   :30.0   Max.   :1427.0   Max.   :12567   Max.   :9.00




      age         area_percentage   height_percentage land_surface_condition
 Min.   :  0.00   Min.   :  1.000   Min.   : 2.000    n: 35528
 1st Qu.: 10.00   1st Qu.:  5.000   1st Qu.: 4.000    o:  8316
 Median : 15.00   Median :  7.000   Median : 5.000    t:216757
 Mean   : 26.54   Mean   :  8.018   Mean   : 5.434
 3rd Qu.: 30.00   3rd Qu.:  9.000   3rd Qu.: 6.000
 Max.   :995.00   Max.   :100.000   Max.   :32.000




 foundation_type roof_type  ground_floor_type other_floor_type position
 h:  1448        n:182842   f:209619          j: 39843         j: 13282
 i: 10579        q: 61576   m:   508          q:165282         o:  2333
 r:219196        x: 16183   v: 24593          s: 12028         s:202090
 u: 14260                   x: 24877          x: 43448         t: 42896
 w: 15118                   z:  1004





 plan_configuration has_superstructure_adobe_mud
 a:   252           Min.   :0.00000
 c:   325           1st Qu.:0.00000
 d:250072           Median :0.00000
 f:    22           Mean   :0.08865
 m:    46           3rd Qu.:0.00000
 n:    38           Max.   :1.00000
 o:   159
 q:  5692
 s:   346
 u:  3649
 has_superstructure_mud_mortar_stone has_superstructure_stone_flag
 Min.   :0.0000                      Min.   :0.00000
 1st Qu.:1.0000                      1st Qu.:0.00000
 Median :1.0000                      Median :0.00000
 Mean   :0.7619                      Mean   :0.03433
 3rd Qu.:1.0000                      3rd Qu.:0.00000
 Max.   :1.0000                      Max.   :1.00000




 has_superstructure_cement_mortar_stone has_superstructure_mud_mortar_brick
 Min.   :0.00000                        Min.   :0.00000
 1st Qu.:0.00000                        1st Qu.:0.00000
 Median :0.00000                        Median :0.00000
 Mean   :0.01823                        Mean   :0.06815
 3rd Qu.:0.00000                        3rd Qu.:0.00000
 Max.   :1.00000                        Max.   :1.00000




 has_superstructure_cement_mortar_brick has_superstructure_timber
 Min.   :0.00000                        Min.   :0.000
 1st Qu.:0.00000                        1st Qu.:0.000
 Median :0.00000                        Median :0.000
 Mean   :0.07527                        Mean   :0.255
 3rd Qu.:0.00000                        3rd Qu.:1.000
 Max.   :1.00000                        Max.   :1.000




 has_superstructure_bamboo has_superstructure_rc_non_engineered
 Min.   :0.00000           Min.   :0.00000
 1st Qu.:0.00000           1st Qu.:0.00000
 Median :0.00000           Median :0.00000
 Mean   :0.08501           Mean   :0.04259
 3rd Qu.:0.00000           3rd Qu.:0.00000
 Max.   :1.00000           Max.   :1.00000




 has_superstructure_rc_engineered has_superstructure_other
 Min.   :0.00000                  Min.   :0.00000
 1st Qu.:0.00000                  1st Qu.:0.00000
 Median :0.00000                  Median :0.00000
 Mean   :0.01586                  Mean   :0.01498
 3rd Qu.:0.00000                  3rd Qu.:0.00000
 Max.   :1.00000                  Max.   :1.00000




 legal_ownership_status count_families   has_secondary_use
 a:  5512               Min.   :0.0000   Min.   :0.0000
 r:  1473               1st Qu.:1.0000   1st Qu.:0.0000
 v:250939               Median :1.0000   Median :0.0000
 w:  2677               Mean   :0.9839   Mean   :0.1119
                        3rd Qu.:1.0000   3rd Qu.:0.0000
                        Max.   :9.0000   Max.   :1.0000




 has_secondary_use_agriculture has_secondary_use_hotel has_secondary_use_rental
 Min.   :0.00000               Min.   :0.00000         Min.   :0.0000
 1st Qu.:0.00000               1st Qu.:0.00000         1st Qu.:0.0000
 Median :0.00000               Median :0.00000         Median :0.0000
 Mean   :0.06438               Mean   :0.03363         Mean   :0.0081
 3rd Qu.:0.00000               3rd Qu.:0.00000         3rd Qu.:0.0000
 Max.   :1.00000               Max.   :1.00000         Max.   :1.0000




 has_secondary_use_institution has_secondary_use_school
 Min.   :0.0000000             Min.   :0.0000000
 1st Qu.:0.0000000             1st Qu.:0.0000000
 Median :0.0000000             Median :0.0000000
 Mean   :0.0009401             Mean   :0.0003607
 3rd Qu.:0.0000000             3rd Qu.:0.0000000
 Max.   :1.0000000             Max.   :1.0000000




 has_secondary_use_industry has_secondary_use_health_post
 Min.   :0.000000           Min.   :0.000000
 1st Qu.:0.000000           1st Qu.:0.000000
 Median :0.000000           Median :0.000000
 Mean   :0.001071           Mean   :0.000188
 3rd Qu.:0.000000           3rd Qu.:0.000000
 Max.   :1.000000           Max.   :1.000000




 has_secondary_use_gov_office has_secondary_use_use_police
 Min.   :0.0000000            Min.   :0.00e+00
 1st Qu.:0.0000000            1st Qu.:0.00e+00
 Median :0.0000000            Median :0.00e+00
 Mean   :0.0001458            Mean   :8.83e-05
 3rd Qu.:0.0000000            3rd Qu.:0.00e+00
 Max.   :1.0000000            Max.   :1.00e+00




 has_secondary_use_other  damage_grade
 Min.   :0.000000        Min.   :1.000
 1st Qu.:0.000000        1st Qu.:2.000
 Median :0.000000        Median :2.000
 Mean   :0.005119        Mean   :2.238
 3rd Qu.:0.000000        3rd Qu.:3.000
 Max.   :1.000000        Max.   :3.000

La variable 'non numérique' prenant le plus de valeur différente est plan_configuration et on vérifier qu'elle prend bien ses 10 valeur attendue. 

Un coup d'oeuil rappide nous dit qu'il n'y a pas de valeur manquante et pas de caractére vide dans les facteur

Petit vérification suplementaire

In [25]:
lapply(data, function(x) sum(is.na(x)))

$geo_level_1_id
[1] 0

$geo_level_2_id
[1] 0

$geo_level_3_id
[1] 0

$count_floors_pre_eq
[1] 0

$age
[1] 0

$area_percentage
[1] 0

$height_percentage
[1] 0

$land_surface_condition
[1] 0

$foundation_type
[1] 0

$roof_type
[1] 0

$ground_floor_type
[1] 0

$other_floor_type
[1] 0

$position
[1] 0

$plan_configuration
[1] 0

$has_superstructure_adobe_mud
[1] 0

$has_superstructure_mud_mortar_stone
[1] 0

$has_superstructure_stone_flag
[1] 0

$has_superstructure_cement_mortar_stone
[1] 0

$has_superstructure_mud_mortar_brick
[1] 0

$has_superstructure_cement_mortar_brick
[1] 0

$has_superstructure_timber
[1] 0

$has_superstructure_bamboo
[1] 0

$has_superstructure_rc_non_engineered
[1] 0

$has_superstructure_rc_engineered
[1] 0

$has_superstructure_other
[1] 0

$legal_ownership_status
[1] 0

$count_families
[1] 0

$has_secondary_use
[1] 0

$has_secondary_use_agriculture
[1] 0

$has_secondary_use_hotel
[1] 0

$has_secondary_use_rental
[1] 0

$has_secondary_use_institution
[1] 0

$has_secondary_use_school
[1] 0

$has_secondary_use_industry
[1] 0

$has_secondary_use_health_post
[1] 0

$has_secondary_use_gov_office
[1] 0

$has_secondary_use_use_police
[1] 0

$has_secondary_use_other
[1] 0

$damage_grade
[1] 0

On traite maintenant les variable categorical

In [26]:
factor_variables <- which(sapply(data[1,],class)=="factor")
factor_variables

land_surface_condition        foundation_type              roof_type
                     8                      9                     10
     ground_floor_type       other_floor_type               position
                    11                     12                     13
    plan_configuration legal_ownership_status
                    14                     26

On va uttiliser caret pour crée des dummies variable mais avant ça on va tranformer la collone damage_grade pour string pour appliquer un problème de multi-classe.

Voir : https://stackoverflow.com/questions/18503177/r-apply-function-on-specific-dataframe-columns

Voir : https://stackoverflow.com/questions/31165015/how-to-convert-integer-to-factor

In [4]:
data[39] <- lapply(data[39], function(x) as.character(x))
data[,39]<-factor(data[,39])

Vérifion qu'on a bien se que l'on voulait

In [43]:
factor_variables <- which(sapply(data[1,],class)=="factor")
factor_variables

land_surface_condition        foundation_type              roof_type
                     8                      9                     10
     ground_floor_type       other_floor_type               position
                    11                     12                     13
    plan_configuration legal_ownership_status           damage_grade
                    14                     26                     39

On peux maintenant uttiliser summary pour compter le nombre de 1,2,3 pour voir si notre data set est unbalance ou non.

In [42]:
summary(data)

 geo_level_1_id geo_level_2_id   geo_level_3_id  count_floors_pre_eq
 Min.   : 0.0   Min.   :   0.0   Min.   :    0   Min.   :1.00
 1st Qu.: 7.0   1st Qu.: 350.0   1st Qu.: 3073   1st Qu.:2.00
 Median :12.0   Median : 702.0   Median : 6270   Median :2.00
 Mean   :13.9   Mean   : 701.1   Mean   : 6258   Mean   :2.13
 3rd Qu.:21.0   3rd Qu.:1050.0   3rd Qu.: 9412   3rd Qu.:2.00
 Max.   :30.0   Max.   :1427.0   Max.   :12567   Max.   :9.00

      age         area_percentage   height_percentage land_surface_condition
 Min.   :  0.00   Min.   :  1.000   Min.   : 2.000    n: 35528
 1st Qu.: 10.00   1st Qu.:  5.000   1st Qu.: 4.000    o:  8316
 Median : 15.00   Median :  7.000   Median : 5.000    t:216757
 Mean   : 26.54   Mean   :  8.018   Mean   : 5.434
 3rd Qu.: 30.00   3rd Qu.:  9.000   3rd Qu.: 6.000
 Max.   :995.00   Max.   :100.000   Max.   :32.000

 foundation_type roof_type  ground_floor_type other_floor_type position
 h:  1448        n:182842   f:209619          j: 39843         j: 13282
 i: 10579        q: 61576   m:   508          q:165282         o:  2333
 r:219196        x: 16183   v: 24593          s: 12028         s:202090
 u: 14260                   x: 24877          x: 43448         t: 42896
 w: 15118                   z:  1004


 plan_configuration has_superstructure_adobe_mud
 d      :250072     Min.   :0.00000
 q      :  5692     1st Qu.:0.00000
 u      :  3649     Median :0.00000
 s      :   346     Mean   :0.08865
 c      :   325     3rd Qu.:0.00000
 a      :   252     Max.   :1.00000
 (Other):   265
 has_superstructure_mud_mortar_stone has_superstructure_stone_flag
 Min.   :0.0000                      Min.   :0.00000
 1st Qu.:1.0000                      1st Qu.:0.00000
 Median :1.0000                      Median :0.00000
 Mean   :0.7619                      Mean   :0.03433
 3rd Qu.:1.0000                      3rd Qu.:0.00000
 Max.   :1.0000                      Max.   :1.00000

 has_superstructure_cement_mortar_stone has_superstructure_mud_mortar_brick
 Min.   :0.00000                        Min.   :0.00000
 1st Qu.:0.00000                        1st Qu.:0.00000
 Median :0.00000                        Median :0.00000
 Mean   :0.01823                        Mean   :0.06815
 3rd Qu.:0.00000                        3rd Qu.:0.00000
 Max.   :1.00000                        Max.   :1.00000

 has_superstructure_cement_mortar_brick has_superstructure_timber
 Min.   :0.00000                        Min.   :0.000
 1st Qu.:0.00000                        1st Qu.:0.000
 Median :0.00000                        Median :0.000
 Mean   :0.07527                        Mean   :0.255
 3rd Qu.:0.00000                        3rd Qu.:1.000
 Max.   :1.00000                        Max.   :1.000

 has_superstructure_bamboo has_superstructure_rc_non_engineered
 Min.   :0.00000           Min.   :0.00000
 1st Qu.:0.00000           1st Qu.:0.00000
 Median :0.00000           Median :0.00000
 Mean   :0.08501           Mean   :0.04259
 3rd Qu.:0.00000           3rd Qu.:0.00000
 Max.   :1.00000           Max.   :1.00000

 has_superstructure_rc_engineered has_superstructure_other
 Min.   :0.00000                  Min.   :0.00000
 1st Qu.:0.00000                  1st Qu.:0.00000
 Median :0.00000                  Median :0.00000
 Mean   :0.01586                  Mean   :0.01498
 3rd Qu.:0.00000                  3rd Qu.:0.00000
 Max.   :1.00000                  Max.   :1.00000

 legal_ownership_status count_families   has_secondary_use
 a:  5512               Min.   :0.0000   Min.   :0.0000
 r:  1473               1st Qu.:1.0000   1st Qu.:0.0000
 v:250939               Median :1.0000   Median :0.0000
 w:  2677               Mean   :0.9839   Mean   :0.1119
                        3rd Qu.:1.0000   3rd Qu.:0.0000
                        Max.   :9.0000   Max.   :1.0000

 has_secondary_use_agriculture has_secondary_use_hotel has_secondary_use_rental
 Min.   :0.00000               Min.   :0.00000         Min.   :0.0000
 1st Qu.:0.00000               1st Qu.:0.00000         1st Qu.:0.0000
 Median :0.00000               Median :0.00000         Median :0.0000
 Mean   :0.06438               Mean   :0.03363         Mean   :0.0081
 3rd Qu.:0.00000               3rd Qu.:0.00000         3rd Qu.:0.0000
 Max.   :1.00000               Max.   :1.00000         Max.   :1.0000

 has_secondary_use_institution has_secondary_use_school
 Min.   :0.0000000             Min.   :0.0000000
 1st Qu.:0.0000000             1st Qu.:0.0000000
 Median :0.0000000             Median :0.0000000
 Mean   :0.0009401             Mean   :0.0003607
 3rd Qu.:0.0000000             3rd Qu.:0.0000000
 Max.   :1.0000000             Max.   :1.0000000

 has_secondary_use_industry has_secondary_use_health_post
 Min.   :0.000000           Min.   :0.000000
 1st Qu.:0.000000           1st Qu.:0.000000
 Median :0.000000           Median :0.000000
 Mean   :0.001071           Mean   :0.000188
 3rd Qu.:0.000000           3rd Qu.:0.000000
 Max.   :1.000000           Max.   :1.000000

 has_secondary_use_gov_office has_secondary_use_use_police
 Min.   :0.0000000            Min.   :0.00e+00
 1st Qu.:0.0000000            1st Qu.:0.00e+00
 Median :0.0000000            Median :0.00e+00
 Mean   :0.0001458            Mean   :8.83e-05
 3rd Qu.:0.0000000            3rd Qu.:0.00e+00
 Max.   :1.0000000            Max.   :1.00e+00

 has_secondary_use_other damage_grade
 Min.   :0.000000        1: 25124
 1st Qu.:0.000000        2:148259
 Median :0.000000        3: 87218
 Mean   :0.005119
 3rd Qu.:0.000000
 Max.   :1.000000

On a bien a faire a un probleme de calssification unbalence se qui étes a prevoir.

On peux maintenant calculer le ratio des damage_grade.

In [53]:
damage_grade_1_ratio <- 25124/260601
damage_grade_2_ratio <- 148259/260601
damage_grade_3_ratio <- 87218/260601

In [55]:
print(damage_grade_1_ratio)
print(damage_grade_2_ratio)
print(damage_grade_3_ratio)

[1] 0.09640792
[1] 0.5689119
[1] 0.3346802

On va maintenant uttiliser caret pour convertir les variable catégarical en bummies variable, il s'agit d'un One-hot encoding.

Voir : https://topepo.github.io/caret/pre-processing.html#dummy

Voir : https://datatricks.co.uk/one-hot-encoding-in-r-three-simple-methods

In [56]:
install.packages("caret")
install.packages("ggplot2")
install.packages("lattice")

Les packages binaires téléchargés sont dans
	/var/folders/yg/ht7nqbgj78xgjh2pdskv5vx80000gn/T//RtmpQzkQg0/downloaded_packages

Les packages binaires téléchargés sont dans
	/var/folders/yg/ht7nqbgj78xgjh2pdskv5vx80000gn/T//RtmpQzkQg0/downloaded_packages

Les packages binaires téléchargés sont dans
	/var/folders/yg/ht7nqbgj78xgjh2pdskv5vx80000gn/T//RtmpQzkQg0/downloaded_packages

In [5]:
library(ggplot2)
library(lattice)
library(caret)

In [6]:
dummy <- dummyVars(" ~ .", data=data)  
data <- data.frame(predict(dummy, newdata = data))

Exploront un peux notre nouveau data set

In [7]:
options(repr.matrix.max.cols=100)
data[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 30             266             1224          1                   25
2 17             409            12182          2                    0
  area_percentage height_percentage land_surface_condition.n
1  5              2                 0
2 13              7                 0
  land_surface_condition.o land_surface_condition.t foundation_type.h
1 0                        1                        0
2 0                        1                        0
  foundation_type.i foundation_type.r foundation_type.u foundation_type.w
1 0                 1                 0                 0
2 0                 1                 0                 0
  roof_type.n roof_type.q roof_type.x ground_floor_type.f ground_floor_type.m
1 1           0           0           1                   0
2 1           0           0           1                   0
  ground_floor_type.v ground_floor_type.x ground_floor_type.z
1 0                   0                   0
2 0                   0                   0
  other_floor_type.j other_floor_type.q other_floor_type.s other_floor_type.x
1 1                  0                  0                  0
2 0                  1                  0                  0
  position.j position.o position.s position.t plan_configuration.a
1 0          0          1          0          0
2 0          0          1          0          0
  plan_configuration.c plan_configuration.d plan_configuration.f
1 0                    1                    0
2 0                    1                    0
  plan_configuration.m plan_configuration.n plan_configuration.o
1 0                    0                    0
2 0                    0                    0
  plan_configuration.q plan_configuration.s plan_configuration.u
1 0                    0                    0
2 0                    0                    0
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
  has_superstructure_other legal_ownership_status.a legal_ownership_status.r
1 0                        0                        0
2 0                        0                        0
  legal_ownership_status.v legal_ownership_status.w count_families
1 1                        0                        0
2 1                        0                        1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade.1
1 0                            0                       0
2 0                            0                       0
  damage_grade.2 damage_grade.3
1 1              0
2 0              1

In [154]:
dim(data)

[1] 260601     71

In [162]:
summary(data)

 geo_level_1_id geo_level_2_id   geo_level_3_id  count_floors_pre_eq
 Min.   : 0.0   Min.   :   0.0   Min.   :    0   Min.   :1.00
 1st Qu.: 7.0   1st Qu.: 350.0   1st Qu.: 3073   1st Qu.:2.00
 Median :12.0   Median : 702.0   Median : 6270   Median :2.00
 Mean   :13.9   Mean   : 701.1   Mean   : 6258   Mean   :2.13
 3rd Qu.:21.0   3rd Qu.:1050.0   3rd Qu.: 9412   3rd Qu.:2.00
 Max.   :30.0   Max.   :1427.0   Max.   :12567   Max.   :9.00
      age         area_percentage   height_percentage land_surface_condition.n
 Min.   :  0.00   Min.   :  1.000   Min.   : 2.000    Min.   :0.0000
 1st Qu.: 10.00   1st Qu.:  5.000   1st Qu.: 4.000    1st Qu.:0.0000
 Median : 15.00   Median :  7.000   Median : 5.000    Median :0.0000
 Mean   : 26.54   Mean   :  8.018   Mean   : 5.434    Mean   :0.1363
 3rd Qu.: 30.00   3rd Qu.:  9.000   3rd Qu.: 6.000    3rd Qu.:0.0000
 Max.   :995.00   Max.   :100.000   Max.   :32.000    Max.   :1.0000
 land_surface_condition.o land_surface_condition.t foundation_type.h
 Min.   :0.00000          Min.   :0.0000           Min.   :0.000000
 1st Qu.:0.00000          1st Qu.:1.0000           1st Qu.:0.000000
 Median :0.00000          Median :1.0000           Median :0.000000
 Mean   :0.03191          Mean   :0.8318           Mean   :0.005556
 3rd Qu.:0.00000          3rd Qu.:1.0000           3rd Qu.:0.000000
 Max.   :1.00000          Max.   :1.0000           Max.   :1.000000
 foundation_type.i foundation_type.r foundation_type.u foundation_type.w
 Min.   :0.00000   Min.   :0.0000    Min.   :0.00000   Min.   :0.00000
 1st Qu.:0.00000   1st Qu.:1.0000    1st Qu.:0.00000   1st Qu.:0.00000
 Median :0.00000   Median :1.0000    Median :0.00000   Median :0.00000
 Mean   :0.04059   Mean   :0.8411    Mean   :0.05472   Mean   :0.05801
 3rd Qu.:0.00000   3rd Qu.:1.0000    3rd Qu.:0.00000   3rd Qu.:0.00000
 Max.   :1.00000   Max.   :1.0000    Max.   :1.00000   Max.   :1.00000
  roof_type.n      roof_type.q      roof_type.x     ground_floor_type.f
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:1.0000
 Median :1.0000   Median :0.0000   Median :0.0000   Median :1.0000
 Mean   :0.7016   Mean   :0.2363   Mean   :0.0621   Mean   :0.8044
 3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:1.0000
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000
 ground_floor_type.m ground_floor_type.v ground_floor_type.x
 Min.   :0.000000    Min.   :0.00000     Min.   :0.00000
 1st Qu.:0.000000    1st Qu.:0.00000     1st Qu.:0.00000
 Median :0.000000    Median :0.00000     Median :0.00000
 Mean   :0.001949    Mean   :0.09437     Mean   :0.09546
 3rd Qu.:0.000000    3rd Qu.:0.00000     3rd Qu.:0.00000
 Max.   :1.000000    Max.   :1.00000     Max.   :1.00000
 ground_floor_type.z other_floor_type.j other_floor_type.q other_floor_type.s
 Min.   :0.000000    Min.   :0.0000     Min.   :0.0000     Min.   :0.00000
 1st Qu.:0.000000    1st Qu.:0.0000     1st Qu.:0.0000     1st Qu.:0.00000
 Median :0.000000    Median :0.0000     Median :1.0000     Median :0.00000
 Mean   :0.003853    Mean   :0.1529     Mean   :0.6342     Mean   :0.04615
 3rd Qu.:0.000000    3rd Qu.:0.0000     3rd Qu.:1.0000     3rd Qu.:0.00000
 Max.   :1.000000    Max.   :1.0000     Max.   :1.0000     Max.   :1.00000
 other_floor_type.x   position.j        position.o         position.s
 Min.   :0.0000     Min.   :0.00000   Min.   :0.000000   Min.   :0.0000
 1st Qu.:0.0000     1st Qu.:0.00000   1st Qu.:0.000000   1st Qu.:1.0000
 Median :0.0000     Median :0.00000   Median :0.000000   Median :1.0000
 Mean   :0.1667     Mean   :0.05097   Mean   :0.008952   Mean   :0.7755
 3rd Qu.:0.0000     3rd Qu.:0.00000   3rd Qu.:0.000000   3rd Qu.:1.0000
 Max.   :1.0000     Max.   :1.00000   Max.   :1.000000   Max.   :1.0000
   position.t     plan_configuration.a plan_configuration.c
 Min.   :0.0000   Min.   :0.000000     Min.   :0.000000
 1st Qu.:0.0000   1st Qu.:0.000000     1st Qu.:0.000000
 Median :0.0000   Median :0.000000     Median :0.000000
 Mean   :0.1646   Mean   :0.000967     Mean   :0.001247
 3rd Qu.:0.0000   3rd Qu.:0.000000     3rd Qu.:0.000000
 Max.   :1.0000   Max.   :1.000000     Max.   :1.000000
 plan_configuration.d plan_configuration.f plan_configuration.m
 Min.   :0.0000       Min.   :0.00e+00     Min.   :0.0000000
 1st Qu.:1.0000       1st Qu.:0.00e+00     1st Qu.:0.0000000
 Median :1.0000       Median :0.00e+00     Median :0.0000000
 Mean   :0.9596       Mean   :8.44e-05     Mean   :0.0001765
 3rd Qu.:1.0000       3rd Qu.:0.00e+00     3rd Qu.:0.0000000
 Max.   :1.0000       Max.   :1.00e+00     Max.   :1.0000000
 plan_configuration.n plan_configuration.o plan_configuration.q
 Min.   :0.0000000    Min.   :0.0000000    Min.   :0.00000
 1st Qu.:0.0000000    1st Qu.:0.0000000    1st Qu.:0.00000
 Median :0.0000000    Median :0.0000000    Median :0.00000
 Mean   :0.0001458    Mean   :0.0006101    Mean   :0.02184
 3rd Qu.:0.0000000    3rd Qu.:0.0000000    3rd Qu.:0.00000
 Max.   :1.0000000    Max.   :1.0000000    Max.   :1.00000
 plan_configuration.s plan_configuration.u has_superstructure_adobe_mud
 Min.   :0.000000     Min.   :0.000        Min.   :0.00000
 1st Qu.:0.000000     1st Qu.:0.000        1st Qu.:0.00000
 Median :0.000000     Median :0.000        Median :0.00000
 Mean   :0.001328     Mean   :0.014        Mean   :0.08865
 3rd Qu.:0.000000     3rd Qu.:0.000        3rd Qu.:0.00000
 Max.   :1.000000     Max.   :1.000        Max.   :1.00000
 has_superstructure_mud_mortar_stone has_superstructure_stone_flag
 Min.   :0.0000                      Min.   :0.00000
 1st Qu.:1.0000                      1st Qu.:0.00000
 Median :1.0000                      Median :0.00000
 Mean   :0.7619                      Mean   :0.03433
 3rd Qu.:1.0000                      3rd Qu.:0.00000
 Max.   :1.0000                      Max.   :1.00000
 has_superstructure_cement_mortar_stone has_superstructure_mud_mortar_brick
 Min.   :0.00000                        Min.   :0.00000
 1st Qu.:0.00000                        1st Qu.:0.00000
 Median :0.00000                        Median :0.00000
 Mean   :0.01823                        Mean   :0.06815
 3rd Qu.:0.00000                        3rd Qu.:0.00000
 Max.   :1.00000                        Max.   :1.00000
 has_superstructure_cement_mortar_brick has_superstructure_timber
 Min.   :0.00000                        Min.   :0.000
 1st Qu.:0.00000                        1st Qu.:0.000
 Median :0.00000                        Median :0.000
 Mean   :0.07527                        Mean   :0.255
 3rd Qu.:0.00000                        3rd Qu.:1.000
 Max.   :1.00000                        Max.   :1.000
 has_superstructure_bamboo has_superstructure_rc_non_engineered
 Min.   :0.00000           Min.   :0.00000
 1st Qu.:0.00000           1st Qu.:0.00000
 Median :0.00000           Median :0.00000
 Mean   :0.08501           Mean   :0.04259
 3rd Qu.:0.00000           3rd Qu.:0.00000
 Max.   :1.00000           Max.   :1.00000
 has_superstructure_rc_engineered has_superstructure_other
 Min.   :0.00000                  Min.   :0.00000
 1st Qu.:0.00000                  1st Qu.:0.00000
 Median :0.00000                  Median :0.00000
 Mean   :0.01586                  Mean   :0.01498
 3rd Qu.:0.00000                  3rd Qu.:0.00000
 Max.   :1.00000                  Max.   :1.00000
 legal_ownership_status.a legal_ownership_status.r legal_ownership_status.v
 Min.   :0.00000          Min.   :0.000000         Min.   :0.0000
 1st Qu.:0.00000          1st Qu.:0.000000         1st Qu.:1.0000
 Median :0.00000          Median :0.000000         Median :1.0000
 Mean   :0.02115          Mean   :0.005652         Mean   :0.9629
 3rd Qu.:0.00000          3rd Qu.:0.000000         3rd Qu.:1.0000
 Max.   :1.00000          Max.   :1.000000         Max.   :1.0000
 legal_ownership_status.w count_families   has_secondary_use
 Min.   :0.00000          Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.00000          1st Qu.:1.0000   1st Qu.:0.0000
 Median :0.00000          Median :1.0000   Median :0.0000
 Mean   :0.01027          Mean   :0.9839   Mean   :0.1119
 3rd Qu.:0.00000          3rd Qu.:1.0000   3rd Qu.:0.0000
 Max.   :1.00000          Max.   :9.0000   Max.   :1.0000
 has_secondary_use_agriculture has_secondary_use_hotel has_secondary_use_rental
 Min.   :0.00000               Min.   :0.00000         Min.   :0.0000
 1st Qu.:0.00000               1st Qu.:0.00000         1st Qu.:0.0000
 Median :0.00000               Median :0.00000         Median :0.0000
 Mean   :0.06438               Mean   :0.03363         Mean   :0.0081
 3rd Qu.:0.00000               3rd Qu.:0.00000         3rd Qu.:0.0000
 Max.   :1.00000               Max.   :1.00000         Max.   :1.0000
 has_secondary_use_institution has_secondary_use_school
 Min.   :0.0000000             Min.   :0.0000000
 1st Qu.:0.0000000             1st Qu.:0.0000000
 Median :0.0000000             Median :0.0000000
 Mean   :0.0009401             Mean   :0.0003607
 3rd Qu.:0.0000000             3rd Qu.:0.0000000
 Max.   :1.0000000             Max.   :1.0000000
 has_secondary_use_industry has_secondary_use_health_post
 Min.   :0.000000           Min.   :0.000000
 1st Qu.:0.000000           1st Qu.:0.000000
 Median :0.000000           Median :0.000000
 Mean   :0.001071           Mean   :0.000188
 3rd Qu.:0.000000           3rd Qu.:0.000000
 Max.   :1.000000           Max.   :1.000000
 has_secondary_use_gov_office has_secondary_use_use_police
 Min.   :0.0000000            Min.   :0.00e+00
 1st Qu.:0.0000000            1st Qu.:0.00e+00
 Median :0.0000000            Median :0.00e+00
 Mean   :0.0001458            Mean   :8.83e-05
 3rd Qu.:0.0000000            3rd Qu.:0.00e+00
 Max.   :1.0000000            Max.   :1.00e+00
 has_secondary_use_other damage_grade.1    damage_grade.2   damage_grade.3
 Min.   :0.000000        Min.   :0.00000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.000000        1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.000000        Median :0.00000   Median :1.0000   Median :0.0000
 Mean   :0.005119        Mean   :0.09641   Mean   :0.5689   Mean   :0.3347
 3rd Qu.:0.000000        3rd Qu.:0.00000   3rd Qu.:1.0000   3rd Qu.:1.0000
 Max.   :1.000000        Max.   :1.00000   Max.   :1.0000   Max.   :1.0000

## Test submision file

On va générer un fichier pour le soumetre sur DrivenData en générant aléatoirement les damage_drade selon le ration precedament obtenue.

In [63]:
damage_grade_1_ratio + damage_grade_2_ratio + damage_grade_3_ratio

[1] 1

In [107]:
dim(submission_format)

[1] 86868     2

In [125]:
#submission_format[2] <- sample(1:3, size = 86868, replace = TRUE, prob = c(damage_grade_1_ratio,damage_grade_2_ratio,damage_grade_3_ratio))

In [126]:
#write.csv(submission_format, file = "submission_format_random_3.csv", row.names = FALSE)

## Feature selection

### Zero- and Near Zero-Variance Predictors

Voir : https://topepo.github.io/caret/pre-processing.html#zero--and-near-zero-variance-predictors

Peux etres un problème pour le model linéaire apparament mais pas pour decison tree

In [13]:
nzv <- nearZeroVar(data, saveMetrics= TRUE)
nzv[nzv$nzv,][1:36,]

                                       freqRatio   percentUnique zeroVar nzv
land_surface_condition.o                  30.33730 0.0007674568  FALSE   TRUE
foundation_type.h                        178.97307 0.0007674568  FALSE   TRUE
foundation_type.i                         23.63380 0.0007674568  FALSE   TRUE
ground_floor_type.m                      511.99409 0.0007674568  FALSE   TRUE
ground_floor_type.z                      258.56275 0.0007674568  FALSE   TRUE
other_floor_type.s                        20.66620 0.0007674568  FALSE   TRUE
position.o                               110.70210 0.0007674568  FALSE   TRUE
plan_configuration.a                    1033.13095 0.0007674568  FALSE   TRUE
plan_configuration.c                     800.84923 0.0007674568  FALSE   TRUE
plan_configuration.d                      23.75078 0.0007674568  FALSE   TRUE
plan_configuration.f                   11844.50000 0.0007674568  FALSE   TRUE
plan_configuration.m                    5664.23913 0.0007674568  FALSE   TRUE
plan_configuration.n                    6856.92105 0.0007674568  FALSE   TRUE
plan_configuration.o                    1638.00000 0.0007674568  FALSE   TRUE
plan_configuration.q                      44.78373 0.0007674568  FALSE   TRUE
plan_configuration.s                     752.18208 0.0007674568  FALSE   TRUE
plan_configuration.u                      70.41710 0.0007674568  FALSE   TRUE
has_superstructure_stone_flag             28.12719 0.0007674568  FALSE   TRUE
has_superstructure_cement_mortar_stone    53.84028 0.0007674568  FALSE   TRUE
has_superstructure_rc_non_engineered      22.47968 0.0007674568  FALSE   TRUE
has_superstructure_rc_engineered          62.05371 0.0007674568  FALSE   TRUE
has_superstructure_other                  65.73521 0.0007674568  FALSE   TRUE
legal_ownership_status.a                  46.27885 0.0007674568  FALSE   TRUE
legal_ownership_status.r                 175.91853 0.0007674568  FALSE   TRUE
legal_ownership_status.v                  25.97174 0.0007674568  FALSE   TRUE
legal_ownership_status.w                  96.34815 0.0007674568  FALSE   TRUE
has_secondary_use_hotel                   28.73879 0.0007674568  FALSE   TRUE
has_secondary_use_rental                 122.44908 0.0007674568  FALSE   TRUE
has_secondary_use_institution           1062.67755 0.0007674568  FALSE   TRUE
has_secondary_use_school                2771.35106 0.0007674568  FALSE   TRUE
has_secondary_use_industry               933.05376 0.0007674568  FALSE   TRUE
has_secondary_use_health_post           5317.38776 0.0007674568  FALSE   TRUE
has_secondary_use_gov_office            6856.92105 0.0007674568  FALSE   TRUE
has_secondary_use_use_police           11329.47826 0.0007674568  FALSE   TRUE
has_secondary_use_other                  194.35307 0.0007674568  FALSE   TRUE
NA                                              NA           NA     NA     NA

In [14]:
dim(data)

[1] 260601     71

In [15]:
nzv <- nearZeroVar(data)
filteredDescr <- data[, -nzv]
dim(filteredDescr)

[1] 260601     36

In [164]:
filteredDescr[1:2,]

  geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq age
1 30             266             1224          1                   25
2 17             409            12182          2                    0
  area_percentage height_percentage land_surface_condition.n
1  5              2                 0
2 13              7                 0
  land_surface_condition.t foundation_type.r foundation_type.u
1 1                        1                 0
2 1                        1                 0
  foundation_type.w roof_type.n roof_type.q roof_type.x ground_floor_type.f
1 0                 1           0           0           1
2 0                 1           0           0           1
  ground_floor_type.v ground_floor_type.x other_floor_type.j other_floor_type.q
1 0                   0                   1                  0
2 0                   0                   0                  1
  other_floor_type.x position.j position.s position.t
1 0                  0          1          0
2 0                  0          1          0
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo count_families
1 0                         0                         0
2 0                         0                         1
  has_secondary_use has_secondary_use_agriculture damage_grade.1 damage_grade.2
1 0                 0                             0              1
2 0                 0                             0              0
  damage_grade.3
1 0
2 1

### Identifying Correlated Predictors

On elever les variable fortement corréler. 

Mais je pense pas qu'ici sa sera uttile.

In [165]:
descrCor <-  cor(filteredDescr)
highCorr <- sum(abs(descrCor[upper.tri(descrCor)]) > .999)

In [166]:
descrCor <- cor(filteredDescr)
summary(descrCor[upper.tri(descrCor)])

     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-0.883396 -0.047275 -0.004061 -0.011432  0.039344  0.772734

In [167]:
highlyCorDescr <- findCorrelation(descrCor, cutoff = .75)
filteredDescr <- filteredDescr[,-highlyCorDescr]
descrCor2 <- cor(filteredDescr)
summary(descrCor2[upper.tri(descrCor2)])

     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-0.658725 -0.043182 -0.003916 -0.006108  0.037400  0.739059

# Faire des teste sur un sous-ensemble du data set pour diminuer le temps de compilation

In [16]:
set.seed(2)
newdata <- filteredDescr[sample(nrow(data),10000),]

In [17]:
dim(newdata)

[1] 10000    36

In [18]:
options(repr.plot.width=20, repr.plot.height=10)
set.seed(3)

X<-newdata[,setdiff(colnames(newdata),"damage_grade.1")]
Y<-newdata[,"damage_grade.1"]

N<-nrow(X)    #Number of examples
n<-ncol(X)    #Number of input variables

Correlation with the output

In [19]:
# drop = F is used to preserve the structure of the data as data.frame (see https://www.r-bloggers.com/2018/02/r-tip-use-drop-false-with-data-frames/)
CV_folds <- 10

size_CV <-floor(N/CV_folds)

CV_err<-matrix(0,nrow=n,ncol=CV_folds)

for (i in 1:CV_folds) {
    
    idx_ts<-(((i-1)*size_CV+1):(i*size_CV))  ### idx_ts represents the indices of the test set the i-th fold
    X_ts<-X[idx_ts,]  
    Y_ts<-Y[idx_ts]  
     
    idx_tr<-setdiff(1:N,idx_ts) ### idx_tr represents  indices of the training sefor the i-th fold
    X_tr<-X[idx_tr,]
    Y_tr<-Y[idx_tr]                          
    
    # Compute correlation across all the input variables and the target variable
    correlation_vector <-abs(cor(X_tr,Y_tr))
    # Rank variables according to correlation with the output
    correlation_ranking_idx <-sort(correlation_vector,dec=T,index.return=T)$ix

}  

correlation_ranking_idx
colnames(X)[correlation_ranking_idx]

 [1] 34 10 17 15 26 16 28 35 20 19 12 11  1  6  4 13 25 14 27 32  5  2 33 31 21
[26]  8  7  9 30 29 22  3 24 23 18

 [1] "damage_grade.2"
 [2] "foundation_type.r"
 [3] "ground_floor_type.v"
 [4] "roof_type.x"
 [5] "has_superstructure_mud_mortar_stone"
 [6] "ground_floor_type.f"
 [7] "has_superstructure_cement_mortar_brick"
 [8] "damage_grade.3"
 [9] "other_floor_type.q"
[10] "other_floor_type.j"
[11] "foundation_type.w"
[12] "foundation_type.u"
[13] "geo_level_1_id"
[14] "area_percentage"
[15] "count_floors_pre_eq"
[16] "roof_type.n"
[17] "has_superstructure_adobe_mud"
[18] "roof_type.q"
[19] "has_superstructure_mud_mortar_brick"
[20] "has_secondary_use"
[21] "age"
[22] "geo_level_2_id"
[23] "has_secondary_use_agriculture"
[24] "count_families"
[25] "other_floor_type.x"
[26] "land_surface_condition.n"
[27] "height_percentage"
[28] "land_surface_condition.t"
[29] "has_superstructure_bamboo"
[30] "has_superstructure_timber"
[31] "position.j"
[32] "geo_level_3_id"
[33] "position.t"
[34] "position.s"
[35] "ground_floor_type.x"

mRMR

In [20]:
# drop = F is used to preserve the structure of the data as data.frame (see https://www.r-bloggers.com/2018/02/r-tip-use-drop-false-with-data-frames/)

CV_folds <- 10

size_CV <-floor(N/CV_folds)

CV_err<-matrix(0,nrow=n,ncol=CV_folds)

for (i in 1:CV_folds) {
    
    idx_ts<-(((i-1)*size_CV+1):(i*size_CV))  ### idx_ts represents the indices of the test set the i-th fold
    X_ts<-X[idx_ts,]  
    Y_ts<-Y[idx_ts]  
     
    idx_tr<-setdiff(1:N,idx_ts) ### idx_tr represents  indices of the training sefor the i-th fold
    X_tr<-X[idx_tr,]
    Y_tr<-Y[idx_tr]                          
    
    # Computing the correlation between input variables and output variable on the training set
    correlation<-abs(cor(X_tr,Y_tr))
    
    # Initialization : No variables are selected and all the variables are candidates
    selected<-c()
    candidates<-1:n
    
    #mRMR ranks the variables by taking account not only the correlation with the output, but also by avoiding redudant variables
    for (j in 1:n) {
        redundancy_score<-numeric(length(candidates))
        
        if (length(selected)>0) {
            # Compute the correlation between the selected variables and the candidates on the training set
            cor_selected_candidates<-cor(X_tr[,selected,drop=F],X_tr[,candidates,drop=F])
            # Compute the mean correlation for each candidate variable, across the selected variables
            redundancy_score<-apply(cor_selected_candidates,2,mean)
        }
        
        # mRMR: minimum Redundancy Maximum Relevancy
        mRMR_score<-correlation[candidates]-redundancy_score
        
        # Select the candidate variable that maximises the mRMR score
        selected_current<-candidates[which.max(mRMR_score)]
        selected<-c(selected,selected_current)
        
        # Remove the selected variables from the candidates
        candidates<-setdiff(candidates,selected_current)
    }
    
    ranking <- selected

}  

selected
colnames(X)[selected]

 [1] 34 35 17 10 12 15 26 16 28 20 19 11  4  1 13 14  6 25 21  2 32 27  8  9  5
[26] 18 31 30 23 24 22 33  3 29  7

 [1] "damage_grade.2"
 [2] "damage_grade.3"
 [3] "ground_floor_type.v"
 [4] "foundation_type.r"
 [5] "foundation_type.w"
 [6] "roof_type.x"
 [7] "has_superstructure_mud_mortar_stone"
 [8] "ground_floor_type.f"
 [9] "has_superstructure_cement_mortar_brick"
[10] "other_floor_type.q"
[11] "other_floor_type.j"
[12] "foundation_type.u"
[13] "count_floors_pre_eq"
[14] "geo_level_1_id"
[15] "roof_type.n"
[16] "roof_type.q"
[17] "area_percentage"
[18] "has_superstructure_adobe_mud"
[19] "other_floor_type.x"
[20] "geo_level_2_id"
[21] "has_secondary_use"
[22] "has_superstructure_mud_mortar_brick"
[23] "land_surface_condition.n"
[24] "land_surface_condition.t"
[25] "age"
[26] "ground_floor_type.x"
[27] "count_families"
[28] "has_superstructure_bamboo"
[29] "position.s"
[30] "position.t"
[31] "position.j"
[32] "has_secondary_use_agriculture"
[33] "geo_level_3_id"
[34] "has_superstructure_timber"
[35] "height_percentage"