In [3]:
#install.packages('ggplot2')
#install.packages('lattice')
#install.packages('caret')
#install.packages('dplyr')
#install.packages('tictoc')
#install.packages('recipes')

In [1]:
library(xgboost)
library(Matrix)

library(ggplot2)
library(lattice)
library(caret)
library(dplyr)
library(tictoc)
library(recipes)

Attachement du package : ‘dplyr’


L'objet suivant est masqué depuis ‘package:xgboost’:

    slice


Les objets suivants sont masqués depuis ‘package:stats’:

    filter, lag


Les objets suivants sont masqués depuis ‘package:base’:

    intersect, setdiff, setequal, union



Attachement du package : ‘recipes’


L'objet suivant est masqué depuis ‘package:Matrix’:

    update


L'objet suivant est masqué depuis ‘package:stats’:

    step

In [2]:
train_values <- read.csv("train_values.csv",stringsAsFactors = T)
test_values <- read.csv("test_values.csv",stringsAsFactors = T)
train_labels <- read.csv("train_labels.csv",stringsAsFactors = T)
submission_format <- read.csv("submission_format.csv",stringsAsFactors = T)

In [3]:
data <- merge(train_values,train_labels,by=c('building_id','building_id'),all.x=T)
test <- read.csv("test_values.csv",stringsAsFactors = T)

In [4]:
mean_damage_level_1 <- 0:30
mean_damage_level_2 <- 0:1427
mean_damage_level_3 <- 0:12567

sd_damage_level_1 <- 0:30
sd_damage_level_2 <- 0:1427
sd_damage_level_3 <- 0:12567


mean_level_1 <- data %>% group_by(geo_level_1_id) %>% 
  summarise(mean_damage=mean(damage_grade),
            .groups = 'drop')

mean_level_2 <- data %>% group_by(geo_level_2_id) %>% 
  summarise(mean_damage=mean(damage_grade),
            .groups = 'drop')

mean_level_3 <- data %>% group_by(geo_level_3_id) %>% 
  summarise(mean_damage=mean(damage_grade),
            .groups = 'drop')

sd_level_1 <- data %>% group_by(geo_level_1_id) %>% 
  summarise(sd_damage=sd(damage_grade),
            .groups = 'drop')

sd_level_2 <- data %>% group_by(geo_level_2_id) %>% 
  summarise(sd_damage=sd(damage_grade),
            .groups = 'drop')

sd_level_3 <- data %>% group_by(geo_level_3_id) %>% 
  summarise(sd_damage=sd(damage_grade),
            .groups = 'drop')


for (i in 1:31){mean_damage_level_1[i] <- mean_level_1[i,2]}  

k <- 1
for (i in 1:1428){if(i-1 == mean_level_2[k,1]){ 
        mean_damage_level_2[i] <- mean_level_2[k,2]
        k <- k+1 } else { mean_damage_level_2[i] <- NA}}

k <- 1
for (i in 1:12568){if(i-1 == mean_level_3[k,1]){ 
        mean_damage_level_3[i] <- mean_level_3[k,2]
        k <- k+1 } else { mean_damage_level_3[i] <- NA}}


for (i in 1:31){sd_damage_level_1[i] <- sd_level_1[i,2]}  

k <- 1
for (i in 1:1428){if(i-1 == sd_level_2[k,1]){ 
        sd_damage_level_2[i] <- sd_level_2[k,2]
        k <- k+1 } else { sd_damage_level_2[i] <- NA}}

k <- 1
for (i in 1:12568){if(i-1 == sd_level_3[k,1]){ 
        sd_damage_level_3[i] <- sd_level_3[k,2]
        k <- k+1 } else { sd_damage_level_3[i] <- NA}}

In [5]:
tic()
for (i in 1:nrow(data)){
    if(is.na(mean_damage_level_3[data[i,c("geo_level_3_id")]+1])){
        if(is.na(mean_damage_level_2[data[i,c("geo_level_2_id")]+1])){
            data$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))
        } else {data$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
    } else {data$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_3[data[i,c("geo_level_3_id")]+1]))
            data$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[data[i,c("geo_level_2_id")]+1]))
            data$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
}

for (i in 1:nrow(data)){
    if(is.na(sd_damage_level_3[data[i,c("geo_level_3_id")]+1])){
        if(is.na(sd_damage_level_2[data[i,c("geo_level_2_id")]+1])){
            data$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))
        } else {data$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
    } else {data$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_3[data[i,c("geo_level_3_id")]+1]))
            data$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[data[i,c("geo_level_2_id")]+1]))
            data$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
}
toc()

In [6]:
for (i in 1:nrow(test)){
    if(is.na(mean_damage_level_3[test[i,c("geo_level_3_id")]+1])){
        if(is.na(mean_damage_level_2[test[i,c("geo_level_2_id")]+1])){
            test$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))
        } else {test$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
    } else {test$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_3[test[i,c("geo_level_3_id")]+1]))
            test$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[test[i,c("geo_level_2_id")]+1]))
            test$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
}

for (i in 1:nrow(test)){
    if(is.na(sd_damage_level_3[test[i,c("geo_level_3_id")]+1])){
        if(is.na(sd_damage_level_2[test[i,c("geo_level_2_id")]+1])){
            test$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))
        } else {test$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
    } else {test$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_3[test[i,c("geo_level_3_id")]+1]))
            test$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[test[i,c("geo_level_2_id")]+1]))
            test$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
}

In [39]:
data <- data %>% relocate(geo_level_1_mean_damage,.after=geo_level_1_id) %>% 
relocate(geo_level_2_mean_damage,.after=geo_level_2_id) %>% 
relocate(geo_level_3_mean_damage,.after=geo_level_3_id) %>% 
relocate(geo_level_1_sd_damage,.after=geo_level_1_mean_damage) %>%
relocate(geo_level_2_sd_damage,.after=geo_level_2_mean_damage) %>% 
relocate(geo_level_3_sd_damage,.after=geo_level_3_mean_damage)

test <- test %>% relocate(geo_level_1_mean_damage,.after=geo_level_1_id) %>% 
relocate(geo_level_2_mean_damage,.after=geo_level_2_id) %>% 
relocate(geo_level_3_mean_damage,.after=geo_level_3_id) %>% 
relocate(geo_level_1_sd_damage,.after=geo_level_1_mean_damage) %>%
relocate(geo_level_2_sd_damage,.after=geo_level_2_mean_damage) %>% 
relocate(geo_level_3_sd_damage,.after=geo_level_3_mean_damage)

In [13]:
options(repr.matrix.max.cols=50)
data[1:3,]

  geo_level_1_id geo_level_1_mean_damage geo_level_1_sd_damage geo_level_2_id
1 30             2.020477                0.4558226             266
2 17             2.794480                0.4352255             409
3 17             2.794480                0.4352255             716
  geo_level_2_mean_damage geo_level_2_sd_damage geo_level_3_id
1 1.984293                0.2987067              1224
2 2.977444                0.1490457             12182
3 2.984772                0.1227723              7056
  geo_level_3_mean_damage geo_level_3_sd_damage count_floors_pre_eq age
1 1.971429                0.1690309             1                   25
2 3.000000                0.0000000             2                    0
3 3.000000                0.0000000             2                    5
  area_percentage height_percentage land_surface_condition foundation_type
1  5              2                 t                      r
2 13              7                 t                      r
3 12              6                 o                      r
  roof_type ground_floor_type other_floor_type position plan_configuration
1 n         f                 j                s        d
2 n         f                 q                s        d
3 q         f                 q                s        d
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
3 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
3 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
3 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
3 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
3 0                                    0
  has_superstructure_other legal_ownership_status count_families
1 0                        v                      0
2 0                        v                      1
3 0                        v                      1
  has_secondary_use has_secondary_use_agriculture has_secondary_use_hotel
1 0                 0                             0
2 0                 0                             0
3 0                 0                             0
  has_secondary_use_rental has_secondary_use_institution
1 0                        0
2 0                        0
3 0                        0
  has_secondary_use_school has_secondary_use_industry
1 0                        0
2 0                        0
3 0                        0
  has_secondary_use_health_post has_secondary_use_gov_office
1 0                             0
2 0                             0
3 0                             0
  has_secondary_use_use_police has_secondary_use_other damage_grade
1 0                            0                       2
2 0                            0                       3
3 0                            0                       3

In [8]:
data <- data[,-1]

In [8]:
data <- data[,setdiff(colnames(data),c("building_id","geo_level_1_id","geo_level_2_id","geo_level_3_id","has_secondary_use"))]
test <- test[,setdiff(colnames(test),c("building_id","geo_level_1_id","geo_level_2_id","geo_level_3_id","has_secondary_use"))]

In [68]:
write.csv(data, file = "data_target_encoding.csv", row.names = FALSE)
write.csv(test, file = "test_target_encoding.csv", row.names = FALSE)

In [71]:
dataNN<-filter(data,age<995)

dataNN <- recipe(damage_grade ~ ., dataNN) %>%
  step_normalize(count_floors_pre_eq, age, area_percentage, height_percentage, geo_level_1_mean_damage, geo_level_2_mean_damage, geo_level_3_mean_damage, geo_level_1_sd_damage,geo_level_2_sd_damage,geo_level_3_sd_damage) %>%
  step_dummy(all_nominal(), one_hot = TRUE) %>%
  prep(log_changes=TRUE) %>%
  bake(new_data = NULL)

testNN <- recipe(~ ., test) %>%
  step_normalize(count_floors_pre_eq, age, area_percentage, height_percentage, geo_level_1_mean_damage, geo_level_2_mean_damage, geo_level_3_mean_damage, geo_level_1_sd_damage,geo_level_2_sd_damage,geo_level_3_sd_damage) %>%
  step_dummy(all_nominal(), one_hot = TRUE) %>%
  prep(log_changes=TRUE) %>%
  bake(new_data = NULL)

step_normalize (normalize_IzYcn): same number of columns

step_dummy (dummy_yz0u9):
 new (38): land_surface_condition_n, land_surface_condition_o, ...
 removed (8): land_surface_condition, foundation_type, roof_type, ...

step_normalize (normalize_dlQxO): same number of columns

step_dummy (dummy_rnwJG):
 new (38): land_surface_condition_n, land_surface_condition_o, ...
 removed (8): land_surface_condition, foundation_type, roof_type, ...

In [13]:
write.csv(dataNN, file = "data_target_encoding_NN.csv", row.names = FALSE)
write.csv(testNN, file = "test_target_encoding_NN.csv", row.names = FALSE)

In [10]:
options(repr.matrix.max.cols=100)
dataNN[1:3,]

  geo_level_1_mean_damage geo_level_1_sd_damage geo_level_2_mean_damage
1  1.9238307              -2.0182397             1.2979668
2 -0.2767838               0.3564008            -0.1642616
3 -0.8358949              -0.5345501            -0.1805833
  geo_level_2_sd_damage geo_level_3_mean_damage geo_level_3_sd_damage
1 -0.1128443             0.9784884               0.9106079
2 -0.9298182            -0.5986421              -2.5526659
3 -0.9402487             1.8984812              -2.5526659
  count_floors_pre_eq age         area_percentage height_percentage
1  1.1906588          -0.08922295 -0.2315965       0.2957086
2 -0.1828791          -0.02111558  1.1389238      -0.2286890
3 -0.1828791          -0.29354507 -0.9168566      -0.2286890
  has_superstructure_adobe_mud has_superstructure_mud_mortar_stone
1 0                            1
2 0                            1
3 0                            1
  has_superstructure_stone_flag has_superstructure_cement_mortar_stone
1 0                             0
2 0                             0
3 0                             0
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
3 0                                   0
  has_superstructure_timber has_superstructure_bamboo
1 0                         0
2 0                         0
3 0                         0
  has_superstructure_rc_non_engineered has_superstructure_rc_engineered
1 0                                    0
2 0                                    0
3 0                                    0
  has_superstructure_other count_families has_secondary_use_agriculture
1 0                        1              0
2 0                        1              1
3 0                        1              0
  has_secondary_use_hotel has_secondary_use_rental
1 0                       0
2 0                       0
3 0                       0
  has_secondary_use_institution has_secondary_use_school
1 0                             0
2 0                             0
3 0                             0
  has_secondary_use_industry has_secondary_use_health_post
1 0                          0
2 0                          0
3 0                          0
  has_secondary_use_gov_office has_secondary_use_use_police
1 0                            0
2 0                            0
3 0                            0
  has_secondary_use_other land_surface_condition_n land_surface_condition_o
1 0                       0                        0
2 0                       0                        0
3 0                       0                        0
  land_surface_condition_t foundation_type_h foundation_type_i
1 1                        0                 0
2 1                        0                 0
3 1                        0                 0
  foundation_type_r foundation_type_u foundation_type_w roof_type_n roof_type_q
1 1                 0                 0                 1           0
2 1                 0                 0                 1           0
3 1                 0                 0                 1           0
  roof_type_x ground_floor_type_f ground_floor_type_m ground_floor_type_v
1 0           1                   0                   0
2 0           1                   0                   0
3 0           1                   0                   0
  ground_floor_type_x ground_floor_type_z other_floor_type_j other_floor_type_q
1 0                   0                   0                  1
2 0                   0                   0                  1
3 0                   0                   0                  1
  other_floor_type_s other_floor_type_x position_j position_o position_s
1 0                  0                  0          0          1
2 0                  0                  0          0          1
3 0                  0                  0          0          1
  position_t plan_configuration_a plan_configuration_c plan_configuration_d
1 0          0                    0                    1
2 0          0                    0                    1
3 0          0                    0                    1
  plan_configuration_f plan_configuration_m plan_configuration_n
1 0                    0                    0
2 0                    0                    0
3 0                    0                    0
  plan_configuration_o plan_configuration_q plan_configuration_s
1 0                    0                    0
2 0                    0                    0
3 0                    0                    0
  plan_configuration_u legal_ownership_status_a legal_ownership_status_r
1 0                    0                        0
2 0                    0                        0
3 0                    0                        0
  legal_ownership_status_v legal_ownership_status_w
1 1                        0
2 1                        0
3 1                        0

In [76]:
# drop = F is used to preserve the structure of the data as data.frame (see https://www.r-bloggers.com/2018/02/r-tip-use-drop-false-with-data-frames/)
n<-ncol(dataNN)
targets<-which(grepl('damage_grade',colnames(dataNN)))
correlation<-abs(cor(dataNN[,-targets,drop=F],dataNN[,targets,drop=F]))
selected<-c()
candidates<-1:n

    #mRMR ranks the variables by taking account not only the correlation with the output, but also by avoiding redudant variables
    for (j in 1:n) {
        redundancy_score<-numeric(length(candidates))
        
        if (length(selected)>0) {
            # Compute the correlation between the selected variables and the candidates on the training set
            cor_selected_candidates<-cor(dataNN[,selected,drop=F],dataNN[,candidates,drop=F])
            # Compute the mean correlation for each candidate variable, across the selected variables
            redundancy_score<-apply(cor_selected_candidates,2,mean)
        }
        
        # mRMR: minimum Redundancy Maximum Relevancy
        mRMR_score<-correlation[candidates]-redundancy_score
        
        # Select the candidate variable that maximises the mRMR score
        selected_current<-candidates[which.max(mRMR_score)]
        selected<-c(selected,selected_current)
        
        # Remove the selected variables from the candidates
        candidates<-setdiff(candidates,selected_current)
    }
    
    rankingNN <- selected

In [77]:
rankingNN
colnames(dataNN)[rankingNN]

 [1]  5  2 38  3 46 12 16  1 43 37  4 51 50 44 42 40 39 20 41  8 19 49  6  7  9
[26] 17 56 24 67 25 45 18 66 13 14 11 22 69 53 70 59 48 60 26 58 65 57 21 68 55
[51] 32 36 34 35 52 63 23 10 28 27 64 30 29 61 33 31 62 15 47 54

 [1] "geo_level_3_mean_damage"
 [2] "geo_level_1_sd_damage"
 [3] "foundation_type_i"
 [4] "geo_level_2_mean_damage"
 [5] "ground_floor_type_m"
 [6] "has_superstructure_mud_mortar_stone"
 [7] "has_superstructure_cement_mortar_brick"
 [8] "geo_level_1_mean_damage"
 [9] "roof_type_q"
[10] "foundation_type_h"
[11] "geo_level_2_sd_damage"
[12] "other_floor_type_q"
[13] "other_floor_type_j"
[14] "roof_type_x"
[15] "roof_type_n"
[16] "foundation_type_u"
[17] "foundation_type_r"
[18] "has_superstructure_rc_engineered"
[19] "foundation_type_w"
[20] "age"
[21] "has_superstructure_rc_non_engineered"
[22] "ground_floor_type_z"
[23] "geo_level_3_sd_damage"
[24] "count_floors_pre_eq"
[25] "area_percentage"
[26] "has_superstructure_timber"
[27] "position_s"
[28] "has_secondary_use_hotel"
[29] "plan_configuration_u"
[30] "has_secondary_use_rental"
[31] "ground_floor_type_f"
[32] "has_superstructure_bamboo"
[33] "plan_configuration_s"
[34] "has_superstructure_stone_flag"
[35] "has_superstructure_cement_mortar_stone"
[36] "has_superstructure_adobe_mud"
[37] "count_families"
[38] "legal_ownership_status_r"
[39] "other_floor_type_x"
[40] "legal_ownership_status_v"
[41] "plan_configuration_c"
[42] "ground_floor_type_x"
[43] "plan_configuration_d"
[44] "has_secondary_use_institution"
[45] "plan_configuration_a"
[46] "plan_configuration_q"
[47] "position_t"
[48] "has_superstructure_other"
[49] "legal_ownership_status_a"
[50] "position_o"
[51] "has_secondary_use_other"
[52] "land_surface_condition_t"
[53] "land_surface_condition_n"
[54] "land_surface_condition_o"
[55] "other_floor_type_s"
[56] "plan_configuration_n"
[57] "has_secondary_use_agriculture"
[58] "height_percentage"
[59] "has_secondary_use_industry"
[60] "has_secondary_use_school"
[61] "plan_configuration_o"
[62] "has_secondary_use_gov_office"
[63] "has_secondary_use_health_post"
[64] "plan_configuration_f"
[65] "damage_grade"
[66] "has_secondary_use_use_police"
[67] "plan_configuration_m"
[68] "has_superstructure_mud_mortar_brick"
[69] "ground_floor_type_v"
[70] "position_j"